use serde::Serialize;

/// Pull request row from database
#[derive(Debug, Clone, Serialize)]
pub struct PrRow {
    pub id: i64,
    pub pr_number: i64,
    pub ticket_id: String,
    pub repo_owner: String,
    pub repo_name: String,
    pub title: String,
    pub url: String,
    pub state: String,
    pub head_sha: String,
    pub ci_status: Option<String>,
    pub ci_check_runs: Option<String>,
    pub review_status: Option<String>,
    pub mergeable: Option<bool>,
    pub mergeable_state: Option<String>,
    pub merged_at: Option<i64>,
    pub created_at: i64,
    pub updated_at: i64,
    pub draft: bool,
    pub is_queued: bool,
    pub merge_readiness_status: Option<String>,
    pub merge_readiness_action: Option<String>,
    pub merge_readiness_blockers: Option<String>,
    pub merge_readiness_warnings: Option<String>,
    pub readiness_source_head_sha: Option<String>,
    pub merge_group_sha: Option<String>,
    pub required_checks_policy_known: Option<bool>,
    pub required_reviews_policy_known: Option<bool>,
    pub merge_queue_required: Option<bool>,
    pub merge_queue_state: Option<String>,
    pub readiness_updated_at: Option<i64>,
    pub github_node_id: Option<String>,
    pub merge_methods_policy_known: Option<bool>,
    pub allowed_merge_methods: Option<String>,
    pub default_merge_method: Option<String>,
    pub unaddressed_comment_count: i64,
}

pub(super) fn read_pr_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<PrRow> {
    Ok(PrRow {
        id: row.get(0)?,
        pr_number: row.get(1)?,
        ticket_id: row.get(2)?,
        repo_owner: row.get(3)?,
        repo_name: row.get(4)?,
        title: row.get(5)?,
        url: row.get(6)?,
        state: row.get(7)?,
        head_sha: row.get(8)?,
        ci_status: row.get(9)?,
        ci_check_runs: row.get(10)?,
        review_status: row.get(11)?,
        mergeable: row.get(12)?,
        mergeable_state: row.get(13)?,
        merged_at: row.get(14)?,
        created_at: row.get(15)?,
        updated_at: row.get(16)?,
        draft: row.get(17)?,
        is_queued: row.get(18)?,
        merge_readiness_status: row.get(19)?,
        merge_readiness_action: row.get(20)?,
        merge_readiness_blockers: row.get(21)?,
        merge_readiness_warnings: row.get(22)?,
        readiness_source_head_sha: row.get(23)?,
        merge_group_sha: row.get(24)?,
        required_checks_policy_known: row.get(25)?,
        required_reviews_policy_known: row.get(26)?,
        merge_queue_required: row.get(27)?,
        merge_queue_state: row.get(28)?,
        readiness_updated_at: row.get(29)?,
        github_node_id: row.get(30)?,
        merge_methods_policy_known: row.get(31)?,
        allowed_merge_methods: row.get(32)?,
        default_merge_method: row.get(33)?,
        unaddressed_comment_count: row.get(34)?,
    })
}

/// PR comment row from database
#[derive(Debug, Clone, Serialize)]
pub struct PrCommentRow {
    pub id: i64,
    pub pr_id: i64,
    pub author: String,
    pub body: String,
    pub comment_type: String,
    pub file_path: Option<String>,
    pub line_number: Option<i32>,
    pub addressed: i32,
    pub outdated: i32,
    pub created_at: i64,
}

pub(super) fn read_pr_comment_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<PrCommentRow> {
    Ok(PrCommentRow {
        id: row.get(0)?,
        pr_id: row.get(1)?,
        author: row.get(2)?,
        body: row.get(3)?,
        comment_type: row.get(4)?,
        file_path: row.get(5)?,
        line_number: row.get(6)?,
        addressed: row.get(7)?,
        outdated: row.get(8)?,
        created_at: row.get(9)?,
    })
}
