/* Generated by pnpm build:plugin-sdk-runtime from packages/plugin-sdk/src/index.ts. Do not edit. */
//#region packages/plugin-sdk/src/browserSurfaces.ts
var BrowserSurfaceError = class extends Error {
	code;
	constructor(code, message) {
		super(message);
		this.name = "BrowserSurfaceError";
		this.code = code;
	}
};
function isAllowedBrowserSurfaceUrl(value) {
	try {
		const url = new URL(value);
		return url.protocol === "http:" || url.protocol === "https:";
	} catch {
		return false;
	}
}
var openforgePackageMetadataSchema_default = {
	$schema: "https://json-schema.org/draft/2020-12/schema",
	$id: "https://openforge.dev/schemas/package-openforge.v1.schema.json",
	title: "OpenForge package metadata",
	description: "Schema for package.json#openforge metadata used by OpenForge plugin packages.",
	type: "object",
	additionalProperties: false,
	required: [
		"id",
		"apiVersion",
		"displayName",
		"description"
	],
	dependentRequired: { "frontendStyles": ["frontend"] },
	allOf: [{
		"if": {
			"properties": { "requires": { "contains": { "const": "browserSurfaces" } } },
			"required": ["requires"]
		},
		"then": { "required": ["frontend"] }
	}, {
		"if": {
			"properties": { "enablement": { "const": "app" } },
			"required": ["enablement"]
		},
		"then": {
			"properties": { "requires": { "contains": { "const": "appEnablement" } } },
			"required": ["requires"]
		}
	}],
	properties: {
		"id": {
			"type": "string",
			"minLength": 1,
			"pattern": "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$",
			"description": "Explicit app-wide plugin id. Host-exposed contribution ids are qualified with this id."
		},
		"apiVersion": { "enum": [1] },
		"displayName": {
			"type": "string",
			"minLength": 1
		},
		"description": {
			"type": "string",
			"minLength": 1
		},
		"enablement": {
			"enum": ["app", "project"],
			"default": "project",
			"description": "Lifecycle ownership for this plugin package. Omission means project-owned enablement."
		},
		"icon": {
			"oneOf": [{
				"type": "string",
				"minLength": 1,
				"pattern": "\\S"
			}, {
				"type": "object",
				"additionalProperties": false,
				"required": ["type", "svg"],
				"properties": {
					"type": { "const": "svg" },
					"svg": {
						"type": "string",
						"minLength": 1,
						"pattern": "\\S"
					}
				}
			}],
			"description": "Lucide icon name in kebab-case or inline SVG geometry using the PluginIcon contract."
		},
		"frontend": {
			"type": "string",
			"minLength": 1,
			"description": "Path to the built frontend JavaScript entry artifact."
		},
		"frontendStyles": {
			"type": "array",
			"minItems": 1,
			"uniqueItems": true,
			"items": {
				"type": "string",
				"minLength": 1,
				"pattern": "\\.css$"
			},
			"description": "Paths to built frontend CSS artifacts. The renderer attaches them before importing the frontend entry and removes them when the plugin deactivates."
		},
		"backend": {
			"type": "string",
			"minLength": 1,
			"pattern": "\\.(?:mjs|js|cjs)$",
			"description": "Path to the built backend JavaScript artifact. Use .mjs for new plugins; .js and .cjs remain supported for compatibility. The host runs each backend in a replaceable worker."
		},
		"requires": {
			"type": "array",
			"uniqueItems": true,
			"items": { "enum": [
				"commands",
				"events",
				"views",
				"injectionPoints",
				"taskPane",
				"taskStart",
				"settings",
				"background",
				"backend",
				"storage",
				"context",
				"navigation",
				"tasks",
				"projects",
				"fs",
				"shell",
				"notifications",
				"attention",
				"system.openUrl",
				"system.writeClipboardText",
				"config",
				"projectConfig",
				"browserSurfaces",
				"appEnablement",
				"customSidebarNavigation",
				"reviewUI"
			] }
		}
	}
};
//#endregion
//#region packages/plugin-sdk/src/pluginIconContract.ts
function isPluginIconName(value) {
	return typeof value === "string" && value.trim().length > 0;
}
function isPluginSvgIcon(value) {
	if (value === null || typeof value !== "object") return false;
	const icon = value;
	return Object.keys(icon).length === 2 && icon.type === "svg" && typeof icon.svg === "string" && icon.svg.trim().length > 0;
}
//#endregion
//#region packages/plugin-sdk/src/types.ts
function readSupportedOpenForgeApiVersions() {
	const versions = openforgePackageMetadataSchema_default.properties.apiVersion.enum;
	if (!Array.isArray(versions) || versions.length === 0 || !versions.every((version) => typeof version === "number" && Number.isInteger(version))) throw new Error("openforgePackageMetadataSchema.json properties.apiVersion.enum must contain at least one integer");
	return [...versions];
}
var SUPPORTED_OPENFORGE_API_VERSIONS = Object.freeze(readSupportedOpenForgeApiVersions());
var OPENFORGE_PLUGIN_API_VERSION = SUPPORTED_OPENFORGE_API_VERSIONS[0];
var MIN_SUPPORTED_API_VERSION = Math.min(...SUPPORTED_OPENFORGE_API_VERSIONS);
var MAX_SUPPORTED_API_VERSION = Math.max(...SUPPORTED_OPENFORGE_API_VERSIONS);
var OPENFORGE_PLUGIN_CAPABILITY_TYPE_MEMBERS = [
	"commands",
	"events",
	"views",
	"injectionPoints",
	"taskPane",
	"taskStart",
	"settings",
	"background",
	"backend",
	"storage",
	"context",
	"navigation",
	"tasks",
	"projects",
	"fs",
	"shell",
	"notifications",
	"attention",
	"system.openUrl",
	"system.writeClipboardText",
	"config",
	"projectConfig",
	"browserSurfaces",
	"appEnablement",
	"customSidebarNavigation",
	"reviewUI"
];
function assertOpenForgePluginCapabilitiesMatchSchema() {
	const schemaCapabilities = openforgePackageMetadataSchema_default.properties.requires.items.enum;
	if (!Array.isArray(schemaCapabilities) || !schemaCapabilities.every((capability) => typeof capability === "string")) throw new Error("openforgePackageMetadataSchema.json properties.requires.items.enum must contain only strings");
	if (schemaCapabilities.length !== OPENFORGE_PLUGIN_CAPABILITY_TYPE_MEMBERS.length || schemaCapabilities.some((capability, index) => capability !== OPENFORGE_PLUGIN_CAPABILITY_TYPE_MEMBERS[index])) throw new Error("OpenForgePluginCapability must match openforgePackageMetadataSchema.json properties.requires.items.enum");
}
assertOpenForgePluginCapabilitiesMatchSchema();
var DEFAULT_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES = 65536;
var MIN_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES = 4;
var MAX_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES = 1048576;
/** Applies the default external text chunk size and rejects values outside host limits. */
function resolveExternalTextFileChunkSize(chunkSizeBytes) {
	const size = chunkSizeBytes ?? 65536;
	if (!Number.isInteger(size) || size < 4 || size > 1048576) throw new RangeError(`chunkSizeBytes must be an integer between 4 and ${MAX_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES}`);
	return size;
}
var TaskFollowUpError = class extends Error {
	code;
	constructor(code, message) {
		super(message);
		this.name = "TaskFollowUpError";
		this.code = code;
	}
};
var MAX_AGENT_SESSION_PAGE_SIZE = 250;
function makePluginViewKey(pluginId, viewId) {
	return `plugin:${pluginId}:${viewId}`;
}
function isPluginViewKey(value) {
	return value.startsWith("plugin:") && value.match(/^plugin:[^:]+:[^:]+$/) !== null;
}
function parsePluginViewKey(key) {
	const parts = key.split(":");
	return {
		pluginId: parts[1],
		viewId: parts[2]
	};
}
//#endregion
//#region packages/plugin-sdk/src/manifest.ts
var OPENFORGE_PACKAGE_METADATA_SCHEMA = openforgePackageMetadataSchema_default;
var OPENFORGE_PLUGIN_CAPABILITIES = openforgePackageMetadataSchema_default.properties.requires.items.enum;
var CAPABILITIES = new Set(OPENFORGE_PLUGIN_CAPABILITIES);
function isString(value) {
	return typeof value === "string";
}
function isNonEmptyString(value) {
	return isString(value) && value.length > 0;
}
function isObject(value) {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}
function validateRequiredString(value, path) {
	if (!isNonEmptyString(value)) return [{
		path,
		message: "Required string"
	}];
	return [];
}
function validateOptionalString(value, path) {
	if (value === void 0) return [];
	if (!isNonEmptyString(value)) return [{
		path,
		message: "Must be a non-empty string"
	}];
	return [];
}
function validateBackendEntry(value) {
	const errors = validateOptionalString(value, "backend");
	if (!isNonEmptyString(value)) return errors;
	if (![
		".mjs",
		".js",
		".cjs"
	].some((extension) => value.endsWith(extension))) errors.push({
		path: "backend",
		message: "Must point to a built .mjs, .js, or .cjs artifact"
	});
	return errors;
}
function validateEnablement(value) {
	if (value === void 0 || value === "app" || value === "project") return [];
	return [{
		path: "enablement",
		message: "Must be \"app\" or \"project\""
	}];
}
function validatePluginIcon(value) {
	if (value === void 0 || isPluginIconName(value) || isPluginSvgIcon(value)) return [];
	return [{
		path: "icon",
		message: "Must be a non-empty Lucide icon name or { type: \"svg\", svg }"
	}];
}
function validateFrontendStyles(value) {
	if (value === void 0) return [];
	if (!Array.isArray(value)) return [{
		path: "frontendStyles",
		message: "Must be an array"
	}];
	const errors = [];
	if (value.length === 0) errors.push({
		path: "frontendStyles",
		message: "Must contain at least one stylesheet path"
	});
	const seen = /* @__PURE__ */ new Set();
	value.forEach((item, index) => {
		if (!isNonEmptyString(item)) errors.push({
			path: `frontendStyles[${index}]`,
			message: "Must be a non-empty string"
		});
		else if (!item.endsWith(".css")) errors.push({
			path: `frontendStyles[${index}]`,
			message: "Must point to a built CSS artifact"
		});
		else if (seen.has(item)) errors.push({
			path: `frontendStyles[${index}]`,
			message: "Duplicate stylesheet path"
		});
		else seen.add(item);
	});
	return errors;
}
function isSupportedOpenForgeApiVersion(apiVersion) {
	return typeof apiVersion === "number" && Number.isInteger(apiVersion) && SUPPORTED_OPENFORGE_API_VERSIONS.includes(apiVersion);
}
function validateApiVersion(value) {
	if (typeof value !== "number" || !Number.isInteger(value)) return [{
		path: "apiVersion",
		message: "Required integer"
	}];
	if (!isSupportedOpenForgeApiVersion(value)) return [{
		path: "apiVersion",
		message: `API version ${value} not supported (supported: ${SUPPORTED_OPENFORGE_API_VERSIONS.join(", ")})`
	}];
	return [];
}
function validateRequires(value) {
	const errors = [];
	if (value === void 0) return errors;
	if (!Array.isArray(value)) return [{
		path: "requires",
		message: "Must be an array"
	}];
	value.forEach((item, index) => {
		const path = `requires[${index}]`;
		if (!isString(item)) {
			errors.push({
				path,
				message: "Must be a string"
			});
			return;
		}
		if (!CAPABILITIES.has(item)) errors.push({
			path,
			message: `Unknown OpenForge capability "${item}"`
		});
	});
	return errors;
}
function validateOpenForgePackageMetadata(data) {
	const errors = [];
	if (!isObject(data)) return [{
		path: "",
		message: "OpenForge package metadata must be an object"
	}];
	errors.push(...validateRequiredString(data.id, "id"));
	errors.push(...validateApiVersion(data.apiVersion));
	errors.push(...validateRequiredString(data.displayName, "displayName"));
	errors.push(...validateRequiredString(data.description, "description"));
	errors.push(...validateEnablement(data.enablement));
	errors.push(...validatePluginIcon(data.icon));
	errors.push(...validateOptionalString(data.frontend, "frontend"));
	errors.push(...validateFrontendStyles(data.frontendStyles));
	if (data.frontendStyles !== void 0 && !isNonEmptyString(data.frontend)) errors.push({
		path: "frontendStyles",
		message: "Requires a frontend entry"
	});
	errors.push(...validateBackendEntry(data.backend));
	errors.push(...validateRequires(data.requires));
	if (data.enablement === "app" && (!Array.isArray(data.requires) || !data.requires.includes("appEnablement"))) errors.push({
		path: "requires",
		message: "App enablement requires the appEnablement capability"
	});
	if (Array.isArray(data.requires) && data.requires.includes("browserSurfaces") && !isNonEmptyString(data.frontend)) errors.push({
		path: "requires",
		message: "browserSurfaces capability requires a frontend entry"
	});
	if (data.contributes !== void 0) errors.push({
		path: "contributes",
		message: "Manifest contribution arrays are not supported; register contributions at runtime"
	});
	for (const key of Object.keys(data)) if (!Object.prototype.hasOwnProperty.call(OPENFORGE_PACKAGE_METADATA_SCHEMA.properties, key)) {
		if (key !== "contributes") errors.push({
			path: key,
			message: "Unknown OpenForge package metadata field"
		});
	}
	return errors;
}
var validatePluginPackageMetadata = validateOpenForgePackageMetadata;
function isOpenForgePackageMetadata(data) {
	return validateOpenForgePackageMetadata(data).length === 0;
}
var isPluginPackageMetadata = isOpenForgePackageMetadata;
//#endregion
//#region packages/plugin-sdk/src/testing/support.ts
function createDisposable(dispose) {
	let disposed = false;
	return { async dispose() {
		if (disposed) return;
		disposed = true;
		await dispose();
	} };
}
var TestingSubscriptionSink = class {
	subscriptions = [];
	add(subscription) {
		if (typeof subscription === "function") {
			this.subscriptions.push(createDisposable(subscription));
			return;
		}
		if (!subscription || typeof subscription.dispose !== "function") throw new Error("context.subscriptions.add requires a disposable or cleanup function");
		this.subscriptions.push(subscription);
	}
	async disposeAll() {
		const subscriptions = this.subscriptions.splice(0).reverse();
		for (const subscription of subscriptions) await subscription.dispose();
	}
};
function createTestingCalls() {
	return {
		commandInvocations: [],
		globalCommandInvocations: [],
		backendInvocations: [],
		emittedEvents: [],
		emittedGlobalEvents: [],
		openUrl: [],
		clipboardWrites: [],
		navigationRequests: [],
		notify: [],
		taskCreations: [],
		taskComposes: [],
		startPromptContributionConfigurations: [],
		taskImplementationStarts: [],
		taskFollowUps: [],
		taskListRequests: [],
		taskActiveRequests: [],
		taskCompletedRequests: [],
		taskDetailRequests: [],
		agentSessionListRequests: [],
		taskSessionListRequests: [],
		taskStatusUpdates: [],
		configWrites: [],
		fsWrites: [],
		fsUserDataReadDirs: [],
		fsUserDataReads: [],
		fsUserDataWrites: [],
		fsUserDataAppends: [],
		fsExternalReadDirs: [],
		fsExternalReads: [],
		fsExternalStats: [],
		fsExternalReadTextFileChunks: [],
		shellSpawns: [],
		shellWrites: [],
		shellResizes: [],
		shellKills: [],
		shellBuffers: [],
		browserSurfaceGetOrCreate: [],
		browserSurfaceAttachments: [],
		browserSurfaceDetaches: [],
		browserSurfaceDestroys: [],
		browserSurfaceNavigations: [],
		browserSurfaceControls: [],
		browserSurfaceSelections: [],
		browserSurfaceFeedbackClears: [],
		browserSurfaceFeedbackReplacements: [],
		browserSurfaceCaptureChecks: [],
		browserSurfaceCaptures: [],
		browserSurfaceCaptureDiscards: [],
		browserSurfaceSessionResets: [],
		storageGets: [],
		storageSets: [],
		storageDeletes: []
	};
}
function createMemoryPluginStorage(calls = createTestingCalls()) {
	const values = /* @__PURE__ */ new Map();
	function scope(scopeKind, scopeId) {
		const prefix = `${scopeKind}:${scopeId ?? ""}:`;
		return {
			async get(key) {
				calls.storageGets.push({
					scope: scopeKind,
					scopeId,
					key
				});
				return values.has(`${prefix}${key}`) ? values.get(`${prefix}${key}`) : null;
			},
			async set(key, value) {
				values.set(`${prefix}${key}`, value);
				calls.storageSets.push({
					scope: scopeKind,
					scopeId,
					key,
					value
				});
			},
			async delete(key) {
				values.delete(`${prefix}${key}`);
				calls.storageDeletes.push({
					scope: scopeKind,
					scopeId,
					key
				});
			}
		};
	}
	return {
		global: scope("global", null),
		project: (projectId) => scope("project", projectId),
		task: (taskId) => scope("task", taskId)
	};
}
function commandDescriptor(command) {
	return {
		id: command.id,
		qualifiedId: command.qualifiedId,
		pluginId: command.pluginId,
		projectId: command.projectId,
		title: command.title,
		icon: command.icon,
		shortcut: command.shortcut,
		discoverable: command.discoverable ?? true,
		input: command.input,
		output: command.output
	};
}
function normalizeAgentCommandMetadata(metadata) {
	if (metadata === void 0) return void 0;
	if (metadata === null || typeof metadata !== "object" || Array.isArray(metadata)) throw new Error("commands registration agent metadata must be an object");
	const candidate = metadata;
	if (typeof candidate.description !== "string" || candidate.description.trim().length === 0) throw new Error("commands registration agent metadata requires a non-empty description");
	if (candidate.examples !== void 0 && (!Array.isArray(candidate.examples) || !candidate.examples.every((example) => isJsonValue(example)))) throw new Error("commands registration agent metadata examples must contain only JSON values");
	if (candidate.discoverable !== void 0 && typeof candidate.discoverable !== "boolean") throw new Error("commands registration agent metadata discoverable must be a boolean");
	return {
		description: candidate.description.trim(),
		examples: candidate.examples ? [...candidate.examples] : [],
		discoverable: candidate.discoverable ?? true
	};
}
function isJsonValue(value, seen = /* @__PURE__ */ new Set()) {
	if (value === null || typeof value === "string" || typeof value === "boolean") return true;
	if (typeof value === "number") return Number.isFinite(value);
	if (typeof value !== "object") return false;
	if (seen.has(value)) return false;
	seen.add(value);
	const valid = Array.isArray(value) ? value.every((entry) => isJsonValue(entry, seen)) : Object.values(value).every((entry) => isJsonValue(entry, seen));
	seen.delete(value);
	return valid;
}
function assertLocalId(kind, id) {
	if (typeof id !== "string" || id.trim().length === 0) throw new Error(`${kind} registration requires a non-empty id`);
	const trimmed = id.trim();
	if (trimmed.startsWith("openforge.")) throw new Error(`${kind} registration cannot use openforge.* reserved namespace`);
	if (trimmed.includes(":") || trimmed.startsWith(".") || trimmed.endsWith(".") || trimmed.includes("..")) throw new Error(`${kind} registration has invalid id "${trimmed}"`);
}
function assertTitle(kind, title) {
	if (typeof title !== "string" || title.trim().length === 0) throw new Error(`${kind} registration requires a non-empty title`);
}
function assertFunction(kind, field, value) {
	if (typeof value !== "function") throw new Error(`${kind} registration requires a ${field} function`);
}
var TestingContributionClaims = class {
	ids = /* @__PURE__ */ new Set();
	claim(kind, qualifiedId) {
		const key = this.key(kind, qualifiedId);
		if (this.ids.has(key)) throw new Error(`Duplicate runtime contribution id: ${qualifiedId}`);
		this.ids.add(key);
	}
	release(kind, qualifiedId) {
		this.ids.delete(this.key(kind, qualifiedId));
	}
	key(kind, qualifiedId) {
		return kind === "commands" ? `commands:${qualifiedId}` : `${kind}:${qualifiedId}`;
	}
};
var TestingRegistryServices = class {
	pluginId;
	projectId;
	taskId;
	viewId;
	packageMetadata;
	calls;
	storage;
	config = /* @__PURE__ */ new Map();
	seededTasks;
	seededTaskLabelAssignments;
	seededAgentSessions;
	agentSessionWorkspaces;
	externalTextFiles;
	userDataTextFiles = /* @__PURE__ */ new Map();
	projectFileContents;
	taskWorkspaces;
	claims = new TestingContributionClaims();
	constructor(options = {}) {
		this.pluginId = options.pluginId ?? "test-plugin";
		this.projectId = options.projectId ?? null;
		this.taskId = options.taskId ?? null;
		this.viewId = options.viewId ?? "board";
		this.packageMetadata = options.packageMetadata ?? {
			id: this.pluginId,
			apiVersion: 1,
			displayName: this.pluginId,
			description: ""
		};
		this.calls = createTestingCalls();
		this.storage = options.storage ?? createMemoryPluginStorage(this.calls);
		this.seededTasks = options.tasks ?? [];
		this.seededTaskLabelAssignments = new Map((options.taskLabelAssignments ?? []).map((assignment) => [assignment.taskId, assignment.labels]));
		this.seededAgentSessions = options.agentSessions ?? [];
		this.agentSessionWorkspaces = options.agentSessionWorkspaces ?? {};
		this.externalTextFiles = options.externalTextFiles ?? [];
		this.projectFileContents = options.projectFileContents ?? {};
		this.taskWorkspaces = options.taskWorkspaces ?? {};
		for (const file of options.userDataTextFiles ?? []) this.userDataTextFiles.set(file.path, file.content);
	}
	localQualifiedId(kind, id) {
		assertLocalId(kind, id);
		return `${this.pluginId}.${id.trim()}`;
	}
	getContextSnapshot() {
		return {
			pluginId: this.pluginId,
			projectId: this.projectId,
			...this.taskId === null ? {} : { taskId: this.taskId }
		};
	}
	getNavigationSnapshot(overrides = {}) {
		return {
			activeProjectId: overrides.projectId ?? this.projectId,
			currentView: overrides.viewId ?? this.viewId,
			selectedTaskId: overrides.taskId ?? this.taskId
		};
	}
	startPromptContributions(projectId) {
		const raw = this.config.get(`project:${projectId}:start_prompt_contributions`);
		return Array.isArray(raw) ? raw.filter((entry) => Boolean(entry) && typeof entry === "object" && typeof entry.id === "string" && typeof entry.content === "string") : [];
	}
};
//#endregion
//#region packages/plugin-sdk/src/testing/backendServicesFake.ts
var TestingBackendServicesFake = class {
	services;
	backendMethods = /* @__PURE__ */ new Map();
	backgroundServices = /* @__PURE__ */ new Map();
	constructor(services) {
		this.services = services;
	}
	createApi() {
		return {
			backend: { registerMethod: (method, registration) => this.registerBackendMethod(method, registration) },
			background: { register: (registration) => this.registerBackgroundService(registration) }
		};
	}
	getSnapshot() {
		return {
			backendMethods: Array.from(this.backendMethods.values()),
			backgroundServices: Array.from(this.backgroundServices.values())
		};
	}
	captureBackgroundServiceIds() {
		return new Set(this.backgroundServices.keys());
	}
	async startNewBackgroundServices(existingServices) {
		for (const [key, service] of this.backgroundServices.entries()) {
			if (existingServices.has(key) || service.started) continue;
			await service.start();
			service.started = true;
		}
	}
	async invokeMethod(method, payload) {
		const qualifiedId = this.services.localQualifiedId("backend", method);
		this.services.calls.backendInvocations.push({
			method,
			qualifiedId,
			payload
		});
		const contribution = this.backendMethods.get(qualifiedId);
		if (!contribution) throw new Error(`Backend method is not registered: ${qualifiedId}`);
		return await contribution.registration.handler(payload);
	}
	registerBackendMethod(method, registration) {
		const qualifiedId = this.services.localQualifiedId("backend", method);
		assertFunction("backend", "handler", registration.handler);
		this.services.claims.claim("backend", qualifiedId);
		const contribution = {
			id: method.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId,
			registration
		};
		this.backendMethods.set(qualifiedId, contribution);
		return createDisposable(() => {
			this.backendMethods.delete(qualifiedId);
			this.services.claims.release("backend", qualifiedId);
		});
	}
	registerBackgroundService(registration) {
		const qualifiedId = this.services.localQualifiedId("background", registration.id);
		if (registration.scope !== "global" && registration.scope !== "project" && registration.scope !== "task") throw new Error("background registration requires scope to be global, project, or task");
		assertFunction("background", "start", registration.start);
		this.services.claims.claim("background", qualifiedId);
		const contribution = {
			...registration,
			id: registration.id.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId,
			started: false
		};
		this.backgroundServices.set(qualifiedId, contribution);
		return createDisposable(async () => {
			this.backgroundServices.delete(qualifiedId);
			this.services.claims.release("background", qualifiedId);
			if (contribution.started) {
				await contribution.stop?.();
				contribution.started = false;
			}
		});
	}
};
//#endregion
//#region packages/plugin-sdk/src/testing/commonApiFake.ts
var UTF8_ENCODER = new TextEncoder();
var UTF8_DECODER = new TextDecoder("utf-8", { fatal: true });
function testingTaskWorkspace(workspaces, taskId) {
	const workspace = workspaces[taskId];
	if (!workspace) throw new Error(`No workspace found for task ${taskId}`);
	if (workspace.error) throw new Error(workspace.error);
	return workspace;
}
function readTestingUserDataDir(files, directoryPath) {
	const prefix = directoryPath ? `${directoryPath}/` : "";
	const entries = /* @__PURE__ */ new Map();
	for (const [filePath, content] of files) {
		if (!filePath.startsWith(prefix)) continue;
		const childPath = filePath.slice(prefix.length);
		const separatorIndex = childPath.indexOf("/");
		const name = separatorIndex === -1 ? childPath : childPath.slice(0, separatorIndex);
		if (!name) continue;
		entries.set(name, separatorIndex === -1 ? {
			name,
			path: `${prefix}${name}`,
			isDir: false,
			size: UTF8_ENCODER.encode(content).byteLength,
			modifiedAt: null
		} : {
			name,
			path: `${prefix}${name}`,
			isDir: true,
			size: null,
			modifiedAt: null
		});
	}
	return [...entries.values()].sort((left, right) => {
		if (left.isDir !== right.isDir) return left.isDir ? -1 : 1;
		return left.name < right.name ? -1 : left.name > right.name ? 1 : 0;
	});
}
var TERMINAL_AGENT_SESSION_STATUSES = /* @__PURE__ */ new Set([
	"completed",
	"failed",
	"interrupted"
]);
function encodeAgentSessionCursor(payload) {
	const bytes = UTF8_ENCODER.encode(JSON.stringify(payload));
	let binary = "";
	for (const byte of bytes) binary += String.fromCharCode(byte);
	return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}
function parseAgentSessionCursor(cursor) {
	try {
		const base64 = cursor.replaceAll("-", "+").replaceAll("_", "/");
		const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, "=");
		const binary = atob(padded);
		const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0));
		const payload = JSON.parse(UTF8_DECODER.decode(bytes));
		const filters = payload.filters;
		if (payload.version !== 1 || !Number.isSafeInteger(payload.createdAt) || typeof payload.id !== "string" || payload.id.length === 0 || !filters || typeof filters.provider !== "string" || !Number.isSafeInteger(filters.startInclusive) || !Number.isSafeInteger(filters.endExclusive) || filters.taskId !== null && typeof filters.taskId !== "string") throw new Error("invalid payload");
		return payload;
	} catch {
		throw new TypeError("cursor is malformed");
	}
}
function providerSessionId(session) {
	switch (session.provider) {
		case "opencode": return session.opencode_session_id;
		case "claude-code": return session.claude_session_id;
		case "pi": return session.pi_session_id;
		case "grok": return session.grok_session_id;
		default: return null;
	}
}
function assertNonNegativeSafeInteger(value, name) {
	if (!Number.isSafeInteger(value) || value < 0) throw new RangeError(`${name} must be a non-negative safe integer`);
}
function testingExternalFileIdentity(file) {
	return file.identity ?? `${file.root}:${file.path}`;
}
function readTestingExternalTextRange(file, startOffsetBytes, maxBytes, expectedIdentity) {
	assertNonNegativeSafeInteger(startOffsetBytes, "startOffsetBytes");
	if (maxBytes !== void 0) assertNonNegativeSafeInteger(maxBytes, "maxBytes");
	const identity = testingExternalFileIdentity(file);
	if (expectedIdentity !== void 0 && expectedIdentity !== identity) throw new Error(`External file identity changed: expected ${expectedIdentity}, received ${identity}`);
	const bytes = UTF8_ENCODER.encode(file.content);
	const endOffsetBytes = maxBytes === void 0 ? bytes.byteLength : Math.min(bytes.byteLength, startOffsetBytes + maxBytes);
	return UTF8_DECODER.decode(bytes.slice(startOffsetBytes, endOffsetBytes));
}
function* splitExternalTextFile(content, maxBytes) {
	let chunk = "";
	let chunkBytes = 0;
	for (const character of content) {
		const characterBytes = UTF8_ENCODER.encode(character).byteLength;
		if (chunkBytes + characterBytes > maxBytes && chunk.length > 0) {
			yield chunk;
			chunk = "";
			chunkBytes = 0;
		}
		chunk += character;
		chunkBytes += characterBytes;
	}
	if (chunk.length > 0) yield chunk;
}
function isTestingImageReferenceDefinition(line) {
	const separator = line.indexOf(":");
	if (separator < 0) return false;
	const marker = line.slice(0, separator);
	const value = line.slice(separator + 1);
	const imageNumber = marker.startsWith("[image#") && marker.endsWith("]") ? marker.slice(7, -1) : null;
	return imageNumber !== null && imageNumber.length > 0 && /^\d+$/u.test(imageNumber) && value.trimStart().startsWith("data:image/") && value.includes(";base64,");
}
function testingTaskPromptPreview(task) {
	const lines = task.initial_prompt.split(/\r?\n/u).filter((line) => !isTestingImageReferenceDefinition(line));
	while (lines.at(-1)?.trim() === "") lines.pop();
	return [...lines.join("\n")].slice(0, 120).join("");
}
function testingTaskTitle(task, preview) {
	const explicitTitle = task.title?.trim();
	if (explicitTitle) return explicitTitle;
	return [...preview.split(/\r?\n/u).map((line) => line.trim()).find(Boolean) || task.id].slice(0, 120).join("");
}
function taskReference(task) {
	const preview = testingTaskPromptPreview(task);
	if (!task.project_id) throw new Error(`Task ${task.id} must belong to a project`);
	return {
		id: task.id,
		status: task.status,
		projectId: task.project_id,
		title: testingTaskTitle(task, preview),
		dependsOn: [...task.depends_on]
	};
}
function taskSummary(task, labels = []) {
	return {
		...taskReference(task),
		createdAt: task.created_at,
		updatedAt: task.updated_at,
		promptPreview: testingTaskPromptPreview(task),
		labels: [...labels],
		sourceTicketUrl: task.source_ticket_url
	};
}
function taskDetail(task, labels = []) {
	return {
		...taskSummary(task, labels),
		prompt: task.initial_prompt,
		agent: task.agent,
		permissionMode: task.permission_mode,
		worktreeSource: task.worktree_source,
		worktreeBranch: task.worktree_branch,
		titleSource: task.title_source,
		titleGeneratedAt: task.title_generated_at
	};
}
function asciiLowercase(value) {
	return value.replace(/[A-Z]/gu, (character) => character.toLowerCase());
}
function compareCompletedTasks(left, right) {
	if (left.updated_at !== right.updated_at) return right.updated_at - left.updated_at;
	if (left.id === right.id) return 0;
	return left.id > right.id ? -1 : 1;
}
function testingCompletedTaskScope(projectId, query) {
	return {
		projectId,
		search: asciiLowercase(query.search?.trim() ?? ""),
		labels: [...new Set((query.labels ?? []).map((name) => name.trim().toLowerCase()).filter(Boolean))].sort()
	};
}
function encodeTestingCompletedTaskCursor(cursor) {
	return `testing:${encodeURIComponent(JSON.stringify(cursor))}`;
}
function decodeTestingCompletedTaskCursor(encoded, scope) {
	try {
		if (!encoded.startsWith("testing:")) throw new Error("wrong cursor format");
		const cursor = JSON.parse(decodeURIComponent(encoded.slice(8)));
		if (cursor.version !== 1 || !Number.isSafeInteger(cursor.updatedAt) || typeof cursor.id !== "string" || JSON.stringify(cursor.scope) !== JSON.stringify(scope)) throw new Error("invalid cursor payload");
		return cursor;
	} catch {
		throw new Error("Invalid Task cursor");
	}
}
function listTestingCompletedTasks(allTasks, projectId, query = {}, labelsByTaskId = /* @__PURE__ */ new Map()) {
	if (!projectId.trim()) throw new RangeError("projectId is required");
	const submittedLabels = query.labels ?? [];
	if (submittedLabels.length > 20) throw new RangeError("Completed Task reads support at most 20 Task Label filters");
	if (submittedLabels.some((name) => [...name.trim()].length > 40)) throw new RangeError("Completed Task Label filters must be 40 characters or fewer");
	if ([...query.search?.trim() ?? ""].length > 200) throw new RangeError("Completed Task search must be 200 characters or fewer");
	const scope = testingCompletedTaskScope(projectId, query);
	const labels = new Set(scope.labels);
	const cursor = query.cursor ? decodeTestingCompletedTaskCursor(query.cursor, scope) : null;
	const matching = allTasks.filter((task) => task.status === "done" && task.project_id === projectId).filter((task) => {
		const summary = taskSummary(task, labelsByTaskId.get(task.id));
		return !scope.search || [
			summary.id,
			summary.title,
			summary.promptPreview
		].some((value) => asciiLowercase(value).includes(scope.search));
	}).filter((task) => {
		if (labels.size === 0) return true;
		const names = taskSummary(task, labelsByTaskId.get(task.id)).labels.map((label) => label.name.toLowerCase());
		return [...labels].every((label) => names.includes(label));
	}).sort(compareCompletedTasks);
	const remaining = cursor ? matching.filter((task) => task.updated_at < cursor.updatedAt || task.updated_at === cursor.updatedAt && task.id < cursor.id) : matching;
	const pageTasks = remaining.slice(0, 50);
	const tasks = pageTasks.map((task) => taskSummary(task, labelsByTaskId.get(task.id)));
	const last = pageTasks.at(-1);
	return {
		tasks,
		nextCursor: remaining.length > 50 && last ? encodeTestingCompletedTaskCursor({
			version: 1,
			scope,
			updatedAt: last.updated_at,
			id: last.id
		}) : null
	};
}
var TestingCommonApiFake = class {
	services;
	commands = /* @__PURE__ */ new Map();
	eventListeners = /* @__PURE__ */ new Map();
	eventHandlers = /* @__PURE__ */ new Map();
	taskChangeHandlers = /* @__PURE__ */ new Map();
	eventListenerSequence = 0;
	constructor(services) {
		this.services = services;
	}
	emitTaskChange(event) {
		for (const handler of this.taskChangeHandlers.get(event.projectId) ?? []) handler(event);
	}
	createApi() {
		const api = {
			commands: {
				register: (registration) => this.registerCommand(registration),
				invoke: async (id, payload) => this.invokeCommand(id, payload),
				invokeGlobal: async (qualifiedId, payload) => this.invokeGlobalCommand(qualifiedId, payload),
				list: async () => Array.from(this.commands.values()).map(commandDescriptor),
				listCatalog: async () => []
			},
			events: {
				on: (event, handler) => this.registerEventListener(event, handler, false),
				onGlobal: (qualifiedEvent, handler) => this.registerEventListener(qualifiedEvent, handler, true),
				emit: async (event, payload) => this.emitEvent(event, payload, false),
				emitGlobal: async (qualifiedEvent, payload) => this.emitEvent(qualifiedEvent, payload, true)
			},
			storage: this.services.storage,
			context: { getSnapshot: () => this.services.getContextSnapshot() },
			agentSessions: { list: async (request) => {
				if (typeof request.provider !== "string" || request.provider.trim().length === 0) throw new TypeError("provider must be a non-empty string");
				if (request.taskId !== void 0 && (typeof request.taskId !== "string" || request.taskId.trim().length === 0)) throw new TypeError("taskId must be a non-empty string");
				if (request.cursor !== void 0 && (typeof request.cursor !== "string" || request.cursor.length === 0)) throw new TypeError("cursor must be a non-empty string");
				if (!request.overlaps || typeof request.overlaps !== "object") throw new TypeError("overlaps must contain startInclusive and endExclusive");
				assertNonNegativeSafeInteger(request.overlaps.startInclusive, "overlaps.startInclusive");
				assertNonNegativeSafeInteger(request.overlaps.endExclusive, "overlaps.endExclusive");
				if (request.overlaps.startInclusive >= request.overlaps.endExclusive) throw new RangeError("overlaps must satisfy startInclusive < endExclusive");
				if (!Number.isSafeInteger(request.pageSize) || request.pageSize < 1 || request.pageSize > 250) throw new RangeError(`pageSize must be between 1 and 250`);
				const filters = {
					provider: request.provider,
					startInclusive: request.overlaps.startInclusive,
					endExclusive: request.overlaps.endExclusive,
					taskId: request.taskId ?? null
				};
				const cursor = request.cursor === void 0 ? null : parseAgentSessionCursor(request.cursor);
				if (cursor !== null && (cursor.filters.provider !== filters.provider || cursor.filters.startInclusive !== filters.startInclusive || cursor.filters.endExclusive !== filters.endExclusive || cursor.filters.taskId !== filters.taskId)) throw new TypeError("cursor does not match request filters");
				this.services.calls.agentSessionListRequests.push({
					...request,
					overlaps: { ...request.overlaps }
				});
				const taskById = new Map(this.services.seededTasks.map((task) => [task.id, task]));
				const rows = this.services.seededAgentSessions.filter((session) => taskById.has(session.ticket_id)).filter((session) => session.provider === request.provider).filter((session) => request.taskId === void 0 || session.ticket_id === request.taskId).filter((session) => session.created_at < request.overlaps.endExclusive && (!TERMINAL_AGENT_SESSION_STATUSES.has(session.status) || session.updated_at > request.overlaps.startInclusive)).filter((session) => cursor === null || session.created_at > cursor.createdAt || session.created_at === cursor.createdAt && session.id > cursor.id).slice().sort((left, right) => left.created_at - right.created_at || (left.id < right.id ? -1 : left.id > right.id ? 1 : 0));
				const pageRows = rows.slice(0, request.pageSize);
				const items = pageRows.map((session) => {
					const task = taskById.get(session.ticket_id);
					if (!task) throw new Error(`Missing seeded Task for Agent Session ${session.id}`);
					const workspace = this.services.agentSessionWorkspaces[task.id];
					return {
						id: session.id,
						provider: session.provider,
						providerSessionId: providerSessionId(session),
						createdAt: session.created_at,
						updatedAt: session.updated_at,
						task: {
							id: task.id,
							title: task.title?.trim() || task.id,
							status: task.status,
							createdAt: task.created_at,
							updatedAt: task.updated_at
						},
						workspace: workspace ? {
							rootPath: workspace.rootPath,
							kind: workspace.kind
						} : null
					};
				});
				const last = pageRows.at(-1);
				return {
					items,
					nextCursor: rows.length > request.pageSize && last ? encodeAgentSessionCursor({
						version: 1,
						createdAt: last.created_at,
						id: last.id,
						filters
					}) : null
				};
			} },
			tasks: {
				onDidChange: (projectId, handler) => {
					const handlers = this.taskChangeHandlers.get(projectId) ?? /* @__PURE__ */ new Set();
					handlers.add(handler);
					this.taskChangeHandlers.set(projectId, handlers);
					return createDisposable(() => {
						handlers.delete(handler);
						if (handlers.size === 0) this.taskChangeHandlers.delete(projectId);
					});
				},
				list: async (request) => {
					const projectId = request?.projectId ?? null;
					const includeDone = request?.includeDone ?? false;
					this.services.calls.taskListRequests.push({
						projectId,
						includeDone
					});
					return this.services.seededTasks.filter((task) => {
						if (projectId !== null && task.project_id !== projectId) return false;
						if (projectId !== null && !includeDone && task.status === "done") return false;
						return true;
					});
				},
				get: async (taskId) => this.services.seededTasks.find((task) => task.id === taskId) ?? null,
				active: async (projectId) => {
					this.services.calls.taskActiveRequests.push({ projectId });
					const activeTasks = this.services.seededTasks.filter((task) => task.project_id === projectId && task.status !== "done");
					const activeIds = new Set(activeTasks.map((task) => task.id));
					const relatedIds = /* @__PURE__ */ new Set();
					for (const task of this.services.seededTasks) if (activeIds.has(task.id)) for (const dependencyId of task.depends_on) relatedIds.add(dependencyId);
					else if (task.depends_on.some((dependencyId) => activeIds.has(dependencyId))) relatedIds.add(task.id);
					return {
						tasks: activeTasks.map((task) => taskDetail(task, this.services.seededTaskLabelAssignments.get(task.id))),
						related: this.services.seededTasks.filter((task) => relatedIds.has(task.id) && !activeIds.has(task.id)).map(taskReference)
					};
				},
				completed: async (projectId, query = {}) => {
					this.services.calls.taskCompletedRequests.push({
						projectId,
						...query
					});
					return listTestingCompletedTasks(this.services.seededTasks, projectId, query, this.services.seededTaskLabelAssignments);
				},
				detail: async (projectId, taskId) => {
					this.services.calls.taskDetailRequests.push({
						projectId,
						taskId
					});
					const task = this.services.seededTasks.find((candidate) => candidate.id === taskId && candidate.project_id === projectId);
					if (!task) return null;
					const relatedIds = new Set(task.depends_on);
					for (const candidate of this.services.seededTasks) if (candidate.depends_on.includes(taskId)) relatedIds.add(candidate.id);
					return {
						task: taskDetail(task, this.services.seededTaskLabelAssignments.get(task.id)),
						related: this.services.seededTasks.filter((candidate) => relatedIds.has(candidate.id)).map(taskReference)
					};
				},
				create: async (request) => {
					this.services.calls.taskCreations.push(request);
					return {
						id: `mock-task-${this.services.calls.taskCreations.length}`,
						initial_prompt: request.initialPrompt,
						status: "backlog",
						prompt: null,
						title: null,
						title_source: null,
						title_generated_at: null,
						agent: null,
						permission_mode: null,
						worktree_source: null,
						worktree_branch: null,
						source_ticket_url: null,
						depends_on: request.dependsOn ?? [],
						project_id: request.projectId,
						created_at: 0,
						updated_at: 0
					};
				},
				compose: async (request) => {
					this.services.calls.taskComposes.push(request);
					return {
						task: await api.tasks.create({
							projectId: request.projectId,
							initialPrompt: request.initialPrompt
						}),
						started: false
					};
				},
				updateStatus: async (taskId, status) => {
					this.services.calls.taskStatusUpdates.push({
						taskId,
						status
					});
				},
				listStartPromptContributions: async (projectId) => this.services.startPromptContributions(projectId),
				configureStartPromptContribution: async (request) => {
					this.services.calls.startPromptContributionConfigurations.push(request);
					const contribution = {
						...request,
						ownerPluginId: this.services.pluginId
					};
					const next = [...this.services.startPromptContributions(request.projectId).filter((entry) => entry.id !== request.id || entry.ownerPluginId !== void 0 && entry.ownerPluginId !== contribution.ownerPluginId), contribution].sort((a, b) => (a.order ?? 0) - (b.order ?? 0) || a.id.localeCompare(b.id) || (a.ownerPluginId ?? "").localeCompare(b.ownerPluginId ?? ""));
					this.services.config.set(`project:${request.projectId}:start_prompt_contributions`, next);
					return next;
				},
				startImplementation: async (request) => {
					this.services.calls.taskImplementationStarts.push(request);
					return {
						taskId: request.taskId,
						workspacePath: "/mock-workspace",
						sessionId: "mock-session"
					};
				},
				sendFollowUp: async (request) => {
					this.services.calls.taskFollowUps.push(request);
					return {
						taskId: request.taskId,
						sessionId: "mock-session",
						disposition: "delivered"
					};
				},
				getWorkspace: async () => null,
				getLatestSession: async () => null,
				listSessions: async (request) => {
					this.services.calls.taskSessionListRequests.push({ ...request });
					return this.services.seededAgentSessions.map((session, index) => ({
						session,
						index
					})).filter(({ session }) => session.ticket_id === request.taskId).filter(({ session }) => request.provider === void 0 || session.provider === request.provider).filter(({ session }) => request.createdAtOrAfter === void 0 || session.created_at >= request.createdAtOrAfter).sort((left, right) => right.session.created_at - left.session.created_at || right.index - left.index).map(({ session }) => session);
				}
			},
			projects: {
				list: async () => [],
				get: async () => null
			},
			fs: {
				readDir: async () => [],
				readFile: async ({ path }) => this.services.projectFileContents[path] ?? {
					type: "text",
					content: "",
					mimeType: null,
					size: 0
				},
				writeFile: async (request) => {
					this.services.calls.fsWrites.push(request);
				},
				searchFiles: async () => [],
				task: {
					readDir: async ({ taskId, path }) => {
						const directoryPath = path ?? "";
						const entries = testingTaskWorkspace(this.services.taskWorkspaces, taskId).directories?.[directoryPath];
						if (!entries) throw new Error(`Task workspace directory not found: ${taskId}:${directoryPath}`);
						return entries;
					},
					readFile: async ({ taskId, path }) => {
						const file = testingTaskWorkspace(this.services.taskWorkspaces, taskId).files?.[path];
						if (!file) throw new Error(`Task workspace file not found: ${taskId}:${path}`);
						return file;
					},
					searchFiles: async ({ taskId, query }) => testingTaskWorkspace(this.services.taskWorkspaces, taskId).searches?.[query] ?? []
				}
			},
			shell: {
				spawn: async (request) => {
					this.services.calls.shellSpawns.push(request);
					return 0;
				},
				write: async (request) => {
					this.services.calls.shellWrites.push(request);
				},
				resize: async (request) => {
					this.services.calls.shellResizes.push(request);
				},
				kill: async (request) => {
					this.services.calls.shellKills.push(request);
				},
				getBuffer: async (request) => {
					this.services.calls.shellBuffers.push(request);
					return {
						buffer: null,
						isLive: false,
						instanceId: null
					};
				}
			},
			notifications: { notify: async (request) => {
				this.services.calls.notify.push(request);
			} },
			attention: { listProjects: async () => [] },
			system: {
				openUrl: async (url) => {
					this.services.calls.openUrl.push(url);
				},
				writeClipboardText: async (text) => {
					this.services.calls.clipboardWrites.push(text);
				}
			},
			navigation: {
				get: () => this.services.getNavigationSnapshot(),
				navigate: async (request) => {
					this.services.calls.navigationRequests.push(request);
					return this.services.getNavigationSnapshot(request);
				}
			},
			config: {
				get: async (key) => this.services.config.has(`global:${key}`) ? this.services.config.get(`global:${key}`) : null,
				set: async (key, value) => {
					this.services.config.set(`global:${key}`, value);
					this.services.calls.configWrites.push({
						key,
						value,
						projectId: null
					});
				}
			},
			projectConfig: {
				get: async (key, projectId = this.services.projectId ?? "") => this.services.config.has(`project:${projectId}:${key}`) ? this.services.config.get(`project:${projectId}:${key}`) : null,
				set: async (key, value, projectId = this.services.projectId ?? "") => {
					this.services.config.set(`project:${projectId}:${key}`, value);
					this.services.calls.configWrites.push({
						key,
						value,
						projectId
					});
				}
			}
		};
		return api;
	}
	createBackendApi() {
		const api = this.createApi();
		return {
			...api,
			fs: {
				...api.fs,
				userData: {
					readDir: async (request = {}) => {
						this.services.calls.fsUserDataReadDirs.push(request);
						return readTestingUserDataDir(this.services.userDataTextFiles, request.path);
					},
					readTextFile: async (request) => {
						this.services.calls.fsUserDataReads.push(request);
						return this.services.userDataTextFiles.get(request.path) ?? "";
					},
					writeTextFile: async (request) => {
						this.services.calls.fsUserDataWrites.push(request);
						this.services.userDataTextFiles.set(request.path, request.content);
					},
					appendTextFile: async (request) => {
						this.services.calls.fsUserDataAppends.push(request);
						const content = `${this.services.userDataTextFiles.get(request.path) ?? ""}${request.content}`;
						this.services.userDataTextFiles.set(request.path, content);
						return { sizeBytes: UTF8_ENCODER.encode(content).byteLength };
					}
				},
				external: {
					readDir: async (request) => {
						this.services.calls.fsExternalReadDirs.push(request);
						return [];
					},
					readTextFile: async (request) => {
						this.services.calls.fsExternalReads.push(request);
						return "";
					},
					stat: async (request) => {
						this.services.calls.fsExternalStats.push(request);
						const file = this.services.externalTextFiles.find((candidate) => candidate.root === request.root && candidate.path === request.path);
						if (!file) throw new Error(`External file not found: ${request.root}/${request.path}`);
						return {
							identity: testingExternalFileIdentity(file),
							sizeBytes: UTF8_ENCODER.encode(file.content).byteLength,
							modifiedAtMs: file.modifiedAtMs ?? null
						};
					},
					readTextFileChunks: (request) => {
						const chunkSizeBytes = resolveExternalTextFileChunkSize(request.chunkSizeBytes);
						const { root, path, signal, expectedIdentity, startOffsetBytes = 0, maxBytes } = request;
						this.services.calls.fsExternalReadTextFileChunks.push({
							root,
							path,
							chunkSizeBytes,
							...expectedIdentity === void 0 ? {} : { expectedIdentity },
							...request.startOffsetBytes === void 0 ? {} : { startOffsetBytes },
							...maxBytes === void 0 ? {} : { maxBytes }
						});
						const file = this.services.externalTextFiles.find((candidate) => candidate.root === root && candidate.path === path);
						return (async function* () {
							signal?.throwIfAborted();
							if (!file) throw new Error(`External file not found: ${root}/${path}`);
							const content = readTestingExternalTextRange(file, startOffsetBytes, maxBytes, expectedIdentity);
							for (const chunk of splitExternalTextFile(content, chunkSizeBytes)) {
								signal?.throwIfAborted();
								if (expectedIdentity !== void 0 && testingExternalFileIdentity(file) !== expectedIdentity) throw new Error(`External file identity changed: expected ${expectedIdentity}, received ${testingExternalFileIdentity(file)}`);
								yield chunk;
							}
							signal?.throwIfAborted();
						})();
					}
				}
			}
		};
	}
	getSnapshot() {
		return {
			commands: Array.from(this.commands.values()),
			eventListeners: Array.from(this.eventListeners.values())
		};
	}
	registerCommand(registration) {
		const qualifiedId = this.services.localQualifiedId("commands", registration.id);
		assertTitle("commands", registration.title);
		assertFunction("commands", "handler", registration.handler);
		const agent = normalizeAgentCommandMetadata(registration.agent);
		if (agent && registration.input !== void 0 && !isJsonValue(registration.input)) throw new Error("commands registration agent-facing input schema must be a JSON value");
		if (agent && registration.output !== void 0 && !isJsonValue(registration.output)) throw new Error("commands registration agent-facing output schema must be a JSON value");
		this.services.claims.claim("commands", qualifiedId);
		const contribution = {
			...registration,
			agent,
			id: registration.id.trim(),
			title: registration.title.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId,
			handler: registration.handler
		};
		this.commands.set(qualifiedId, contribution);
		return createDisposable(() => {
			this.commands.delete(qualifiedId);
			this.services.claims.release("commands", qualifiedId);
		});
	}
	registerEventListener(event, handler, global) {
		const qualifiedId = global ? event : this.services.localQualifiedId("events", event);
		if (qualifiedId.trim().length === 0) throw new Error("events registration requires a non-empty id");
		assertFunction("events", "handler", handler);
		const handlers = this.eventHandlers.get(qualifiedId) ?? /* @__PURE__ */ new Set();
		handlers.add(handler);
		this.eventHandlers.set(qualifiedId, handlers);
		const listenerKey = `${qualifiedId}#${++this.eventListenerSequence}`;
		const contribution = {
			id: event,
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId,
			handler,
			global
		};
		this.eventListeners.set(listenerKey, contribution);
		return createDisposable(() => {
			handlers.delete(handler);
			if (handlers.size === 0) this.eventHandlers.delete(qualifiedId);
			this.eventListeners.delete(listenerKey);
		});
	}
	async invokeCommand(id, payload) {
		const qualifiedId = this.services.localQualifiedId("commands", id);
		this.services.calls.commandInvocations.push({
			id,
			qualifiedId,
			payload
		});
		return this.invokeGlobalCommand(qualifiedId, payload);
	}
	async invokeGlobalCommand(qualifiedId, payload) {
		this.services.calls.globalCommandInvocations.push({
			qualifiedId,
			payload
		});
		const command = this.commands.get(qualifiedId);
		if (!command) throw new Error(`Unknown command: ${qualifiedId}`);
		return await command.handler(payload, {
			taskId: null,
			projectId: command.projectId,
			source: "plugin"
		});
	}
	async emitEvent(event, payload, global) {
		const qualifiedEvent = global ? event : this.services.localQualifiedId("events", event);
		if (global) this.services.calls.emittedGlobalEvents.push({
			qualifiedEvent,
			payload
		});
		else this.services.calls.emittedEvents.push({
			event,
			qualifiedEvent,
			payload
		});
		for (const handler of Array.from(this.eventHandlers.get(qualifiedEvent) ?? [])) handler(payload);
	}
};
//#endregion
//#region packages/plugin-sdk/src/browserSurfacesTesting.ts
function disposable(dispose) {
	let disposed = false;
	return { async dispose() {
		if (disposed) return;
		disposed = true;
		await dispose();
	} };
}
function surfaceKey(taskId, id) {
	return `${taskId}\u0000${id}`;
}
function copyState(state) {
	return {
		...state,
		error: state.error ? { ...state.error } : null
	};
}
function validateIdentity(taskId, id) {
	if (!taskId.trim()) throw new BrowserSurfaceError("INVALID_TASK", "Task Browser Surface requires a non-empty Task ID");
	if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(id)) throw new BrowserSurfaceError("INVALID_ID", "Task Browser Surface id must be a stable non-empty local identifier");
}
var TestingTaskBrowserSurface = class {
	taskId;
	id;
	calls;
	onDestroyed;
	state;
	history;
	historyIndex = 0;
	listeners = /* @__PURE__ */ new Set();
	currentAttachment = 0;
	destroyed = false;
	nextAnnotationNumber = 1;
	capturedArtifactIds = /* @__PURE__ */ new Set();
	constructor(taskId, id, initialUrl, calls, onDestroyed) {
		this.taskId = taskId;
		this.id = id;
		this.calls = calls;
		this.onDestroyed = onDestroyed;
		const url = initialUrl ?? "about:blank";
		this.history = [url];
		this.state = {
			url,
			title: "",
			loading: false,
			canGoBack: false,
			canGoForward: false,
			devToolsOpen: false,
			error: null
		};
	}
	async attach(element) {
		this.assertLive();
		const attachment = ++this.currentAttachment;
		this.calls.browserSurfaceAttachments.push({
			taskId: this.taskId,
			id: this.id,
			element
		});
		return disposable(async () => {
			if (this.destroyed || attachment !== this.currentAttachment) return;
			await this.detach();
		});
	}
	async detach() {
		this.assertLive();
		this.currentAttachment += 1;
		this.calls.browserSurfaceDetaches.push({
			taskId: this.taskId,
			id: this.id
		});
	}
	async destroy() {
		if (this.destroyed) return;
		this.destroyed = true;
		this.listeners.clear();
		this.calls.browserSurfaceDestroys.push({
			taskId: this.taskId,
			id: this.id
		});
		this.onDestroyed();
	}
	async getState() {
		this.assertLive();
		return copyState(this.state);
	}
	onStateChanged(handler) {
		this.assertLive();
		this.listeners.add(handler);
		return disposable(() => {
			this.listeners.delete(handler);
		});
	}
	async navigate(url) {
		this.assertLive();
		if (!isAllowedBrowserSurfaceUrl(url)) throw new BrowserSurfaceError("INVALID_URL", "Task Browser Surfaces only allow HTTP(S) navigation");
		this.calls.browserSurfaceNavigations.push({
			taskId: this.taskId,
			id: this.id,
			url
		});
		this.history.splice(this.historyIndex + 1);
		this.history.push(url);
		this.historyIndex = this.history.length - 1;
		this.publish({
			url,
			title: "",
			error: null
		});
		return this.getState();
	}
	async goBack() {
		this.assertLive();
		this.calls.browserSurfaceControls.push({
			taskId: this.taskId,
			id: this.id,
			action: "goBack"
		});
		if (this.historyIndex > 0) this.historyIndex -= 1;
		this.publish({
			url: this.history[this.historyIndex],
			error: null
		});
		return this.getState();
	}
	async goForward() {
		this.assertLive();
		this.calls.browserSurfaceControls.push({
			taskId: this.taskId,
			id: this.id,
			action: "goForward"
		});
		if (this.historyIndex < this.history.length - 1) this.historyIndex += 1;
		this.publish({
			url: this.history[this.historyIndex],
			error: null
		});
		return this.getState();
	}
	async reload() {
		this.assertLive();
		this.calls.browserSurfaceControls.push({
			taskId: this.taskId,
			id: this.id,
			action: "reload"
		});
		this.publish({ error: null });
		return this.getState();
	}
	async stop() {
		this.assertLive();
		this.calls.browserSurfaceControls.push({
			taskId: this.taskId,
			id: this.id,
			action: "stop"
		});
		this.publish({ loading: false });
		return this.getState();
	}
	async openDevTools(panel) {
		this.assertLive();
		this.calls.browserSurfaceControls.push({
			taskId: this.taskId,
			id: this.id,
			action: "openDevTools",
			...panel ? { panel } : {}
		});
		this.publish({ devToolsOpen: true });
		return this.getState();
	}
	async closeDevTools() {
		this.assertLive();
		this.calls.browserSurfaceControls.push({
			taskId: this.taskId,
			id: this.id,
			action: "closeDevTools"
		});
		this.publish({ devToolsOpen: false });
		return this.getState();
	}
	async selectVisibleRegion() {
		this.assertLive();
		this.calls.browserSurfaceSelections.push({
			taskId: this.taskId,
			id: this.id
		});
		return {
			region: {
				x: .1,
				y: .1,
				width: .4,
				height: .4
			},
			comment: "Example visual feedback",
			annotationNumber: this.nextAnnotationNumber++
		};
	}
	async cancelVisibleRegionSelection() {
		this.assertLive();
	}
	async clearVisualFeedback() {
		this.assertLive();
		this.calls.browserSurfaceFeedbackClears.push({
			taskId: this.taskId,
			id: this.id
		});
		this.nextAnnotationNumber = 1;
	}
	async replaceVisualFeedback(feedback) {
		this.assertLive();
		this.calls.browserSurfaceFeedbackReplacements.push({
			taskId: this.taskId,
			id: this.id,
			feedback: feedback.map((marker) => ({
				...marker,
				region: { ...marker.region }
			}))
		});
		this.nextAnnotationNumber = feedback.reduce((maximum, marker) => Math.max(maximum, marker.annotationNumber), 0) + 1;
	}
	async captureExists(artifactId) {
		this.assertLive();
		if (!artifactId.trim()) throw new BrowserSurfaceError("INVALID_ID", "Browser Surface capture requires an artifact ID");
		this.calls.browserSurfaceCaptureChecks.push({
			taskId: this.taskId,
			id: this.id,
			artifactId
		});
		return this.capturedArtifactIds.has(artifactId);
	}
	async captureVisibleViewport() {
		this.assertLive();
		this.calls.browserSurfaceCaptures.push({
			taskId: this.taskId,
			id: this.id
		});
		const artifactId = `capture-${this.calls.browserSurfaceCaptures.length}`;
		this.capturedArtifactIds.add(artifactId);
		return {
			artifactId,
			absolutePath: `/tmp/openforge-browser-captures/${this.taskId}/capture-${this.calls.browserSurfaceCaptures.length}.png`,
			mediaType: "image/png",
			width: 800,
			height: 600,
			url: this.state.url,
			title: this.state.title,
			capturedAt: "2026-01-01T00:00:00.000Z",
			dataUrl: "data:image/png;base64,iVBORw0KGgo="
		};
	}
	async discardCapture(artifactId) {
		this.assertLive();
		if (!artifactId.trim()) throw new BrowserSurfaceError("INVALID_ID", "Browser Surface capture requires an artifact ID");
		this.calls.browserSurfaceCaptureDiscards.push({
			taskId: this.taskId,
			id: this.id,
			artifactId
		});
		this.capturedArtifactIds.delete(artifactId);
	}
	setState(patch) {
		this.assertLive();
		this.state = copyState({
			...this.state,
			...patch
		});
		this.notify();
	}
	publish(patch) {
		this.state = {
			...this.state,
			...patch,
			canGoBack: this.historyIndex > 0,
			canGoForward: this.historyIndex < this.history.length - 1
		};
		this.notify();
	}
	notify() {
		for (const listener of this.listeners) listener(copyState(this.state));
	}
	assertLive() {
		if (this.destroyed) throw new BrowserSurfaceError("SURFACE_DESTROYED", "Task Browser Surface has been destroyed");
	}
};
function createTestingBrowserSurfaces(calls) {
	const surfaces = /* @__PURE__ */ new Map();
	return {
		api: {
			async getOrCreate(request) {
				const recorded = request.initialUrl === void 0 ? {
					taskId: request.taskId,
					id: request.id
				} : { ...request };
				calls.browserSurfaceGetOrCreate.push(recorded);
				validateIdentity(request.taskId, request.id);
				const key = surfaceKey(request.taskId, request.id);
				let surface = surfaces.get(key);
				if (!surface) {
					if (request.initialUrl !== void 0 && !isAllowedBrowserSurfaceUrl(request.initialUrl)) throw new BrowserSurfaceError("INVALID_URL", "Task Browser Surfaces only allow HTTP(S) initial URLs");
					surface = new TestingTaskBrowserSurface(request.taskId, request.id, request.initialUrl, calls, () => surfaces.delete(key));
					surfaces.set(key, surface);
				}
				return surface;
			},
			async resetSession() {
				calls.browserSurfaceSessionResets.push({});
				for (const surface of Array.from(surfaces.values())) await surface.destroy();
			}
		},
		setState(taskId, id, patch) {
			const surface = surfaces.get(surfaceKey(taskId, id));
			if (!surface) throw new BrowserSurfaceError("SURFACE_DESTROYED", "Task Browser Surface is not live");
			surface.setState(patch);
		}
	};
}
//#endregion
//#region packages/plugin-sdk/src/testing/frontendContributionFake.ts
var TestingFrontendContributionFake = class {
	services;
	invokeBackendMethod;
	views = /* @__PURE__ */ new Map();
	taskPaneTabs = /* @__PURE__ */ new Map();
	taskUISections = /* @__PURE__ */ new Map();
	reviewRowActions = /* @__PURE__ */ new Map();
	settingsSections = /* @__PURE__ */ new Map();
	injectionPoints = /* @__PURE__ */ new Map();
	taskStartPrefixProviders = /* @__PURE__ */ new Map();
	browserSurfaces;
	api = null;
	constructor(services, invokeBackendMethod) {
		this.services = services;
		this.invokeBackendMethod = invokeBackendMethod;
		this.browserSurfaces = createTestingBrowserSurfaces(services.calls);
	}
	createApi() {
		if (this.api) return this.api;
		const api = {
			browserSurfaces: this.browserSurfaces.api,
			views: { register: (registration) => this.registerView(registration) },
			taskUI: {
				registerTab: (registration) => this.registerTaskPaneTab(registration),
				registerSection: (registration) => this.registerTaskUISection(registration)
			},
			reviewUI: { registerRowAction: (registration) => this.registerReviewRowAction(registration) },
			taskPane: { registerTab: (registration) => this.registerTaskPaneTab(registration) },
			settings: { registerSection: (registration) => this.registerSettingsSection(registration) },
			backend: {
				state: "ready",
				whenReady: async () => void 0,
				onReady: (handler) => {
					handler();
					return createDisposable(() => void 0);
				},
				invoke: async (method, payload) => this.invokeBackendMethod(method, payload)
			},
			injectionPoints: { register: (registration) => this.registerInjectionPoint(registration) },
			taskStart: { registerPrefixProvider: (registration) => this.registerTaskStartPrefixProvider(registration) }
		};
		this.api = api;
		return api;
	}
	setBrowserSurfaceState(taskId, id, patch) {
		this.browserSurfaces.setState(taskId, id, patch);
	}
	getSnapshot() {
		return {
			views: Array.from(this.views.values()),
			taskPaneTabs: Array.from(this.taskPaneTabs.values()),
			taskUISections: Array.from(this.taskUISections.values()),
			reviewRowActions: Array.from(this.reviewRowActions.values()),
			settingsSections: Array.from(this.settingsSections.values()),
			injectionPoints: Array.from(this.injectionPoints.values()),
			taskStartPrefixProviders: Array.from(this.taskStartPrefixProviders.values()).sort((left, right) => left.order - right.order || left.id.localeCompare(right.id))
		};
	}
	registerView(registration) {
		const qualifiedId = this.services.localQualifiedId("views", registration.id);
		assertTitle("views", registration.title);
		assertFunction("views", "component", registration.component);
		if (registration.navigationComponent !== void 0) {
			assertFunction("views", "navigationComponent", registration.navigationComponent);
			if (registration.placement !== "sidebar") throw new Error("views registration custom navigation requires sidebar placement");
			if (!this.services.packageMetadata.requires?.includes("customSidebarNavigation")) throw new Error("views registration custom navigation requires the customSidebarNavigation capability");
		}
		this.services.claims.claim("views", qualifiedId);
		const contribution = {
			...registration,
			id: registration.id.trim(),
			title: registration.title.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId
		};
		this.views.set(qualifiedId, contribution);
		return createDisposable(() => {
			this.views.delete(qualifiedId);
			this.services.claims.release("views", qualifiedId);
		});
	}
	registerTaskPaneTab(registration) {
		const qualifiedId = this.services.localQualifiedId("taskPane", registration.id);
		assertTitle("taskPane", registration.title);
		assertFunction("taskPane", "component", registration.component);
		this.services.claims.claim("taskPane", qualifiedId);
		const contribution = {
			...registration,
			id: registration.id.trim(),
			title: registration.title.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId
		};
		this.taskPaneTabs.set(qualifiedId, contribution);
		return createDisposable(() => {
			this.taskPaneTabs.delete(qualifiedId);
			this.services.claims.release("taskPane", qualifiedId);
		});
	}
	registerTaskUISection(registration) {
		const qualifiedId = this.services.localQualifiedId("taskUI", registration.id);
		assertFunction("taskUI", "component", registration.component);
		this.services.claims.claim("taskUI", qualifiedId);
		const contribution = {
			...registration,
			id: registration.id.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId
		};
		this.taskUISections.set(qualifiedId, contribution);
		return createDisposable(() => {
			this.taskUISections.delete(qualifiedId);
			this.services.claims.release("taskUI", qualifiedId);
		});
	}
	registerReviewRowAction(registration) {
		const qualifiedId = this.services.localQualifiedId("reviewUI", registration.id);
		assertFunction("reviewUI", "component", registration.component);
		this.services.claims.claim("reviewUI", qualifiedId);
		const contribution = {
			...registration,
			id: registration.id.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId
		};
		this.reviewRowActions.set(qualifiedId, contribution);
		return createDisposable(() => {
			this.reviewRowActions.delete(qualifiedId);
			this.services.claims.release("reviewUI", qualifiedId);
		});
	}
	registerSettingsSection(registration) {
		const qualifiedId = this.services.localQualifiedId("settings", registration.id);
		assertTitle("settings", registration.title);
		assertFunction("settings", "component", registration.component);
		this.services.claims.claim("settings", qualifiedId);
		const contribution = {
			...registration,
			id: registration.id.trim(),
			title: registration.title.trim(),
			qualifiedId,
			pluginId: this.services.pluginId,
			projectId: this.services.projectId
		};
		this.settingsSections.set(qualifiedId, contribution);
		return createDisposable(() => {
			this.settingsSections.delete(qualifiedId);
			this.services.claims.release("settings", qualifiedId);
		});
	}
	registerTaskStartPrefixProvider(registration) {
		this.taskStartPrefixProviders.set(registration.id, {
			id: registration.id,
			title: registration.title,
			order: registration.order ?? 0,
			provide: (context) => registration.provide(context)
		});
		return createDisposable(() => {
			this.taskStartPrefixProviders.delete(registration.id);
		});
	}
	registerInjectionPoint(registration) {
		this.injectionPoints.set(registration.id, {
			id: registration.id,
			location: registration.location
		});
		return createDisposable(() => {
			this.injectionPoints.delete(registration.id);
		});
	}
};
//#endregion
//#region packages/plugin-sdk/src/testing/registryFake.ts
var TestingOpenForgeRegistryFake = class {
	pluginId;
	projectId;
	taskId;
	viewId;
	packageMetadata;
	calls;
	storage;
	frontendSubscriptions = new TestingSubscriptionSink();
	backendSubscriptions = new TestingSubscriptionSink();
	services;
	commonApi;
	frontendContributions;
	backendServices;
	cachedFrontendApi = null;
	cachedBackendApi = null;
	constructor(options = {}) {
		this.services = new TestingRegistryServices(options);
		this.pluginId = this.services.pluginId;
		this.projectId = this.services.projectId;
		this.taskId = this.services.taskId;
		this.viewId = this.services.viewId;
		this.packageMetadata = this.services.packageMetadata;
		this.calls = this.services.calls;
		this.storage = this.services.storage;
		this.commonApi = new TestingCommonApiFake(this.services);
		this.backendServices = new TestingBackendServicesFake(this.services);
		this.frontendContributions = new TestingFrontendContributionFake(this.services, (method, payload) => this.backendServices.invokeMethod(method, payload));
	}
	get frontendApi() {
		return this.createFrontendApi();
	}
	get backendApi() {
		return this.createBackendApi();
	}
	get snapshot() {
		return this.getSnapshot();
	}
	createFrontendApi() {
		if (this.cachedFrontendApi) return this.cachedFrontendApi;
		const api = {
			...this.commonApi.createApi(),
			...this.frontendContributions.createApi(),
			__testing: {
				calls: this.calls,
				registry: this
			}
		};
		this.cachedFrontendApi = api;
		return api;
	}
	createBackendApi() {
		if (this.cachedBackendApi) return this.cachedBackendApi;
		const api = {
			...this.commonApi.createBackendApi(),
			...this.backendServices.createApi(),
			__testing: {
				calls: this.calls,
				registry: this
			}
		};
		this.cachedBackendApi = api;
		return api;
	}
	createFrontendContext() {
		return this.createContext(this.frontendSubscriptions);
	}
	createBackendContext() {
		return this.createContext(this.backendSubscriptions);
	}
	async activateFrontend(plugin) {
		await plugin.activate(this.frontendApi, this.createFrontendContext());
	}
	async activateBackend(plugin) {
		const existingServices = this.backendServices.captureBackgroundServiceIds();
		await plugin.activate(this.backendApi, this.createBackendContext());
		await this.backendServices.startNewBackgroundServices(existingServices);
	}
	emitTaskChange(event) {
		this.commonApi.emitTaskChange(event);
	}
	setBrowserSurfaceState(taskId, id, patch) {
		this.frontendContributions.setBrowserSurfaceState(taskId, id, patch);
	}
	async disposeAll() {
		await this.backendSubscriptions.disposeAll();
		await this.frontendSubscriptions.disposeAll();
	}
	getSnapshot() {
		return {
			pluginId: this.pluginId,
			projectId: this.projectId,
			...this.frontendContributions.getSnapshot(),
			...this.commonApi.getSnapshot(),
			...this.backendServices.getSnapshot()
		};
	}
	createContext(subscriptions) {
		return {
			pluginId: this.pluginId,
			apiVersion: 1,
			packageMetadata: this.packageMetadata,
			subscriptions,
			onDidChange: () => ({ dispose: () => void 0 })
		};
	}
};
function createOpenForgeRegistryFake(options = {}) {
	return new TestingOpenForgeRegistryFake(options);
}
function createMockOpenForgeApi(options = {}) {
	return createMockFrontendOpenForgeApi(options);
}
function createMockFrontendOpenForgeApi(options = {}) {
	return createOpenForgeRegistryFake(options).frontendApi;
}
function createMockBackendOpenForgeApi(options = {}) {
	return createOpenForgeRegistryFake(options).backendApi;
}
function createMockPluginContext(options = {}) {
	return createOpenForgeRegistryFake(options).createFrontendContext();
}
//#endregion
//#region packages/plugin-sdk/src/numberParsing.ts
var STRICT_FINITE_NUMBER_PATTERN = /^[+-]?(?:\d+(?:\.\d+)?|\.\d+)$/;
function parseStrictFiniteNumber(value) {
	if (!STRICT_FINITE_NUMBER_PATTERN.test(value)) return null;
	const parsed = Number(value);
	return Number.isFinite(parsed) ? parsed : null;
}
//#endregion
//#region packages/plugin-sdk/src/projectFileTree.ts
function getProjectFileTreeDepth(path) {
	return path.split("/").length - 1;
}
function getProjectFileTreeParentPath(path) {
	const lastSlash = path.lastIndexOf("/");
	return lastSlash === -1 ? null : path.slice(0, lastSlash);
}
function buildProjectFileTree(flatEntries) {
	const nodesByPath = /* @__PURE__ */ new Map();
	const roots = [];
	for (const entry of flatEntries) nodesByPath.set(entry.path, {
		entry,
		children: [],
		level: 1,
		parentPath: getProjectFileTreeParentPath(entry.path),
		posInSet: 1,
		setSize: 1
	});
	for (const entry of flatEntries) {
		const node = nodesByPath.get(entry.path);
		if (!node) continue;
		const parent = node.parentPath ? nodesByPath.get(node.parentPath) : null;
		if (parent) parent.children.push(node);
		else roots.push(node);
	}
	assignProjectFileTreeMetadata(roots, 1);
	return roots;
}
function assignProjectFileTreeMetadata(nodes, level) {
	const setSize = nodes.length;
	nodes.forEach((node, index) => {
		node.level = level;
		node.posInSet = index + 1;
		node.setSize = setSize;
		assignProjectFileTreeMetadata(node.children, level + 1);
	});
}
function flattenVisibleProjectFileTree(nodes, expandedDirs) {
	const result = [];
	function visit(items) {
		for (const item of items) {
			result.push(item);
			if (item.entry.isDir && expandedDirs.has(item.entry.path)) visit(item.children);
		}
	}
	visit(nodes);
	return result;
}
function getProjectFileTreeItemAccessibility(node, state) {
	const isSelectedFile = !node.entry.isDir && state.selectedPath === node.entry.path;
	return {
		level: node.level,
		setSize: node.setSize,
		posInSet: node.posInSet,
		expanded: node.entry.isDir ? state.expandedDirs.has(node.entry.path) : void 0,
		current: isSelectedFile ? "true" : void 0,
		selected: !node.entry.isDir ? isSelectedFile ? "true" : "false" : void 0,
		labelledBy: !node.entry.isDir && node.entry.size !== null ? `${state.labelId} ${state.sizeId}` : state.labelId
	};
}
function formatProjectFileTreeSize(size) {
	if (size === null) return "";
	if (size < 1024) return `${size} B`;
	if (size < 1048576) return `${(size / 1024).toFixed(1)} KB`;
	return `${(size / 1048576).toFixed(1)} MB`;
}
function projectFileTreePathToId(path) {
	return `project-file-tree-${Array.from(path).map((char) => char.charCodeAt(0).toString(36)).join("-")}`;
}
function hasProjectFileTreeShortcutModifier(event) {
	return event.altKey || event.ctrlKey || event.metaKey || event.shiftKey;
}
function getProjectFileTreeKeyboardAction(event, node, state) {
	if (hasProjectFileTreeShortcutModifier(event)) return { handled: false };
	switch (event.key) {
		case "ArrowDown": return focusByOffset(node.entry.path, state.visiblePaths, 1);
		case "ArrowUp": return focusByOffset(node.entry.path, state.visiblePaths, -1);
		case "Home": return focusFirst(state.visiblePaths);
		case "End": return focusLast(state.visiblePaths);
		case "ArrowRight": return getArrowRightAction(node, state.expandedDirs);
		case "ArrowLeft": return getArrowLeftAction(node, state.expandedDirs, state.visiblePaths);
		case "Enter":
		case " ": return {
			handled: true,
			type: "activate",
			path: node.entry.path
		};
		default: return { handled: false };
	}
}
function focusByOffset(currentPath, visiblePaths, offset) {
	const currentIndex = visiblePaths.indexOf(currentPath);
	if (currentIndex === -1) return {
		handled: true,
		type: "none"
	};
	const nextPath = visiblePaths[Math.max(0, Math.min(visiblePaths.length - 1, currentIndex + offset))];
	return nextPath ? {
		handled: true,
		type: "focus",
		path: nextPath
	} : {
		handled: true,
		type: "none"
	};
}
function focusFirst(visiblePaths) {
	const firstPath = visiblePaths[0];
	return firstPath ? {
		handled: true,
		type: "focus",
		path: firstPath
	} : {
		handled: true,
		type: "none"
	};
}
function focusLast(visiblePaths) {
	const lastPath = visiblePaths.at(-1);
	return lastPath ? {
		handled: true,
		type: "focus",
		path: lastPath
	} : {
		handled: true,
		type: "none"
	};
}
function getArrowRightAction(node, expandedDirs) {
	if (!node.entry.isDir) return {
		handled: true,
		type: "none"
	};
	if (!expandedDirs.has(node.entry.path)) return {
		handled: true,
		type: "toggle",
		path: node.entry.path
	};
	const firstChild = node.children[0];
	return firstChild ? {
		handled: true,
		type: "focus",
		path: firstChild.entry.path
	} : {
		handled: true,
		type: "none"
	};
}
function getArrowLeftAction(node, expandedDirs, visiblePaths) {
	if (node.entry.isDir && expandedDirs.has(node.entry.path)) return {
		handled: true,
		type: "toggle",
		path: node.entry.path
	};
	if (node.parentPath && visiblePaths.includes(node.parentPath)) return {
		handled: true,
		type: "focus",
		path: node.parentPath
	};
	return {
		handled: true,
		type: "none"
	};
}
//#endregion
//#region packages/plugin-sdk/src/domain.ts
function isMergedPullRequest(pr) {
	return pr.state === "merged" || pr.merged_at != null;
}
function isClosedUnmergedPullRequest(pr) {
	return pr.state === "closed" && pr.merged_at == null;
}
function hasMergeConflicts(pr) {
	if (pr.state !== "open") return false;
	const mergeableState = pr.mergeable_state?.toLowerCase() ?? null;
	return mergeableState === "dirty" || mergeableState === "conflicting";
}
function mergeReadinessDetail(code, message) {
	return {
		code,
		message
	};
}
function mergeReadinessResult(pr, status, action, blockers, warnings) {
	return {
		status,
		action,
		blockers,
		warnings,
		freshness: {
			sourceSha: pr.head_sha ?? null,
			checkedAt: pr.updated_at ?? null
		}
	};
}
var MERGE_READINESS_STATUSES = [
	"ready_to_merge",
	"ready_to_enqueue",
	"queued_pull_request",
	"readiness_unknown",
	"blocked"
];
var MERGE_READINESS_ACTIONS = [
	"merge",
	"enqueue",
	"wait_for_queue",
	"wait_for_github",
	"resolve_blockers"
];
function isMergeReadinessStatus(value) {
	return MERGE_READINESS_STATUSES.includes(value);
}
function isMergeReadinessAction(value) {
	return MERGE_READINESS_ACTIONS.includes(value);
}
function parseMergeReadinessDetails(value) {
	if (Array.isArray(value)) return value;
	if (!value) return [];
	try {
		const parsed = JSON.parse(value);
		return Array.isArray(parsed) ? parsed.filter((detail) => typeof detail?.code === "string" && typeof detail?.message === "string") : [];
	} catch {
		return [];
	}
}
function isUnresolvedConversationDetail(detail) {
	return detail.code === "unresolved_conversations";
}
function hasNoPublishedChecksForUnstableMergeability(pr) {
	const mergeableState = pr.mergeable_state?.toLowerCase() ?? null;
	const ciStatus = pr.ci_status?.toLowerCase() ?? null;
	return mergeableState === "unstable" && (ciStatus === null || ciStatus === "none");
}
function downgradeNoCheckPersistedFailures(pr, blockers) {
	if (!hasNoPublishedChecksForUnstableMergeability(pr)) return blockers;
	return blockers.map((blocker) => blocker.code === "checks_failed" ? mergeReadinessDetail("checks_pending", "Required checks are still running.") : blocker);
}
function removeUnresolvedConversationDetails(details) {
	return details.filter((detail) => !isUnresolvedConversationDetail(detail));
}
function shouldIgnorePersistedUnresolvedConversationDetails(pr, blockers, warnings) {
	return pr.unaddressed_comment_count === 0 && (blockers.some(isUnresolvedConversationDetail) || warnings.some(isUnresolvedConversationDetail));
}
function isPersistedMergeReadinessCurrent(pr) {
	const sourceSha = pr.readiness_source_head_sha ?? null;
	const headSha = pr.head_sha ?? null;
	if (!sourceSha || !headSha || sourceSha !== headSha) return false;
	const checkedAt = pr.readiness_updated_at ?? null;
	const updatedAt = pr.updated_at ?? null;
	return checkedAt !== null && (updatedAt === null || checkedAt >= updatedAt);
}
function getPersistedMergeReadiness(pr) {
	const status = pr.merge_readiness_status ?? null;
	const action = pr.merge_readiness_action ?? null;
	if (!isMergeReadinessStatus(status) || !isMergeReadinessAction(action)) return null;
	if (!isPersistedMergeReadinessCurrent(pr)) return null;
	let blockers = downgradeNoCheckPersistedFailures(pr, parseMergeReadinessDetails(pr.merge_readiness_blockers));
	let warnings = parseMergeReadinessDetails(pr.merge_readiness_warnings);
	if (shouldIgnorePersistedUnresolvedConversationDetails(pr, blockers, warnings)) {
		blockers = removeUnresolvedConversationDetails(blockers);
		warnings = removeUnresolvedConversationDetails(warnings);
		if (status === "blocked" && blockers.length === 0) return null;
	}
	return {
		status,
		action,
		blockers,
		warnings,
		freshness: {
			sourceSha: pr.readiness_source_head_sha ?? null,
			checkedAt: pr.readiness_updated_at ?? null
		}
	};
}
function hasMergeReadinessOptions(options) {
	return options.requireBranchUpToDate === true || options.requireConversationResolution === true || options.requireMergeQueue === true;
}
/**
* Explains whether a pull request is ready for a direct merge, queue enqueueing,
* waiting on GitHub/merge queue, or blocked by hard requirements.
*/
function getMergeReadiness(pr, options = {}) {
	const warnings = [];
	const blockers = [];
	if (pr.state !== "open") {
		blockers.push(mergeReadinessDetail(pr.state === "merged" ? "already_merged" : "pull_request_closed", pr.state === "merged" ? "Pull request is already merged." : "Pull request is closed."));
		return mergeReadinessResult(pr, "blocked", "resolve_blockers", blockers, warnings);
	}
	const persisted = hasMergeReadinessOptions(options) ? null : getPersistedMergeReadiness(pr);
	if (persisted) return persisted;
	const mergeableState = pr.mergeable_state?.toLowerCase() ?? null;
	const ciStatus = pr.ci_status?.toLowerCase() ?? null;
	const reviewStatus = pr.review_status?.toLowerCase() ?? null;
	const unaddressedCommentCount = pr.unaddressed_comment_count ?? 0;
	if (pr.draft === true) blockers.push(mergeReadinessDetail("draft", "Pull request is still marked as draft."));
	if (reviewStatus === "changes_requested") blockers.push(mergeReadinessDetail("changes_requested", "Review changes have been requested."));
	if (ciStatus === "pending" || ciStatus === "queued" || ciStatus === "in_progress") blockers.push(mergeReadinessDetail("checks_pending", "Required checks are still running."));
	else if (ciStatus === "failure" || ciStatus === "error" || ciStatus === "cancelled" || ciStatus === "timed_out" || ciStatus === "action_required") blockers.push(mergeReadinessDetail("checks_failed", "Required checks are failing."));
	const hasFailedChecks = blockers.some((blocker) => blocker.code === "checks_failed");
	const hasPendingChecks = blockers.some((blocker) => blocker.code === "checks_pending");
	if (mergeableState === "unstable" && !hasFailedChecks && !hasPendingChecks) blockers.push(hasNoPublishedChecksForUnstableMergeability(pr) ? mergeReadinessDetail("checks_pending", "Required checks are still running.") : mergeReadinessDetail("checks_failed", "GitHub reports failing or unstable required checks."));
	if (mergeableState === "dirty" || mergeableState === "conflicting") blockers.push(mergeReadinessDetail("merge_conflict", "Pull request has merge conflicts."));
	else if (mergeableState === "blocked") blockers.push(mergeReadinessDetail("mergeability_blocked", "GitHub reports that mergeability is blocked."));
	else if (mergeableState === "behind") {
		if (options.requireBranchUpToDate === true) blockers.push(mergeReadinessDetail("branch_out_of_date", "Branch must be updated before merging."));
		else warnings.push(mergeReadinessDetail("branch_behind", "Branch is behind the base branch."));
	}
	if (unaddressedCommentCount > 0) {
		const detail = mergeReadinessDetail("unresolved_conversations", "Pull request has unresolved conversations.");
		if (options.requireConversationResolution === true) blockers.push(detail);
		else warnings.push(detail);
	}
	if (blockers.length > 0) return mergeReadinessResult(pr, "blocked", "resolve_blockers", blockers, warnings);
	if (pr.is_queued === true) return mergeReadinessResult(pr, "queued_pull_request", "wait_for_queue", blockers, warnings);
	const hasDirectMergeability = mergeableState === "clean" || mergeableState === "behind";
	const hasNoCiStatus = ciStatus === null || ciStatus === "none";
	const hasNoReviewStatus = reviewStatus === null || reviewStatus === "none";
	const isUnprotectedFallback = mergeableState === null && pr.mergeable === true && hasNoCiStatus && hasNoReviewStatus;
	if (isUnprotectedFallback) warnings.push(mergeReadinessDetail("unprotected_fallback", "Using simple mergeability because no protected-branch checks or review state are available."));
	if (hasDirectMergeability || isUnprotectedFallback) {
		const mergeQueueRequired = options.requireMergeQueue === true || pr.merge_queue_required === true;
		return mergeReadinessResult(pr, mergeQueueRequired ? "ready_to_enqueue" : "ready_to_merge", mergeQueueRequired ? "enqueue" : "merge", blockers, warnings);
	}
	if (mergeableState === "unknown" || pr.mergeable === null || mergeableState === null && pr.mergeable !== false) {
		warnings.push(mergeReadinessDetail("mergeability_unknown", "GitHub has not reported definitive mergeability yet."));
		return mergeReadinessResult(pr, "readiness_unknown", "wait_for_github", blockers, warnings);
	}
	blockers.push(mergeReadinessDetail("mergeability_blocked", "Pull request is not mergeable."));
	return mergeReadinessResult(pr, "blocked", "resolve_blockers", blockers, warnings);
}
/** Check if a PR is ready for a direct merge action. */
function isReadyToMerge(pr, options) {
	const readiness = getMergeReadiness(pr, options);
	return readiness.status === "ready_to_merge" && readiness.action === "merge";
}
/** Check if a user-initiated merge affordance may be shown/executed now. */
function canMergePullRequest(pr) {
	const readiness = getMergeReadiness(pr);
	return readiness.status === "ready_to_merge" && readiness.action === "merge";
}
/** Check if GitHub reports a PR as queued in a merge queue. */
function isQueuedForMerge(pr) {
	return pr.state === "open" && pr.is_queued;
}
/** Preserves optimistic and definitive states across transient background syncs */
function preservePullRequestState(oldPr, newPr) {
	if (!oldPr) return newPr;
	const result = { ...newPr };
	if (oldPr.state === "merged" && result.state === "open") {
		result.state = "merged";
		result.merged_at = oldPr.merged_at;
	}
	const isTransient = result.mergeable === null || result.mergeable_state === "unknown" || result.mergeable_state === null;
	const oldIsDefinitive = oldPr.mergeable_state !== "unknown" && oldPr.mergeable_state !== null;
	if (isTransient && oldIsDefinitive) {
		result.mergeable = oldPr.mergeable;
		result.mergeable_state = oldPr.mergeable_state;
	}
	const oldReadiness = getPersistedMergeReadiness(oldPr);
	const newReadiness = getPersistedMergeReadiness(result);
	const sameReadinessSource = (oldPr.readiness_source_head_sha ?? oldPr.head_sha ?? null) === (result.readiness_source_head_sha ?? result.head_sha ?? null);
	const newReadinessIsTransient = newReadiness === null || newReadiness.status === "readiness_unknown";
	if (sameReadinessSource && oldReadiness && oldReadiness.status !== "readiness_unknown" && newReadinessIsTransient) {
		result.merge_readiness_status = oldPr.merge_readiness_status;
		result.merge_readiness_action = oldPr.merge_readiness_action;
		result.merge_readiness_blockers = oldPr.merge_readiness_blockers;
		result.merge_readiness_warnings = oldPr.merge_readiness_warnings;
		result.readiness_source_head_sha = oldPr.readiness_source_head_sha;
		result.readiness_updated_at = oldPr.readiness_updated_at;
		result.merge_group_sha = oldPr.merge_group_sha;
		result.required_checks_policy_known = oldPr.required_checks_policy_known;
		result.required_reviews_policy_known = oldPr.required_reviews_policy_known;
		result.merge_queue_required = oldPr.merge_queue_required;
		result.merge_queue_state = oldPr.merge_queue_state;
	}
	return result;
}
function parseCheckRuns(json) {
	if (!json) return [];
	try {
		return JSON.parse(json);
	} catch {
		return [];
	}
}
/** Split check runs into visible (non-passing) and a count of hidden passing checks. */
function splitCheckRuns(checks) {
	const visible = [];
	let passingCount = 0;
	for (const check of checks) if (check.status === "completed" && check.conclusion === "success") passingCount++;
	else visible.push(check);
	return {
		visible,
		passingCount
	};
}
//#endregion
export { BrowserSurfaceError, DEFAULT_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES, MAX_AGENT_SESSION_PAGE_SIZE, MAX_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES, MAX_SUPPORTED_API_VERSION, MIN_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES, MIN_SUPPORTED_API_VERSION, OPENFORGE_PACKAGE_METADATA_SCHEMA, OPENFORGE_PLUGIN_API_VERSION, OPENFORGE_PLUGIN_CAPABILITIES, SUPPORTED_OPENFORGE_API_VERSIONS, TaskFollowUpError, TestingOpenForgeRegistryFake, TestingSubscriptionSink, buildProjectFileTree, canMergePullRequest, createMemoryPluginStorage, createMockBackendOpenForgeApi, createMockFrontendOpenForgeApi, createMockOpenForgeApi, createMockPluginContext, createOpenForgeRegistryFake, createTestingCalls, flattenVisibleProjectFileTree, formatProjectFileTreeSize, getMergeReadiness, getProjectFileTreeDepth, getProjectFileTreeItemAccessibility, getProjectFileTreeKeyboardAction, getProjectFileTreeParentPath, hasMergeConflicts, hasProjectFileTreeShortcutModifier, isAllowedBrowserSurfaceUrl, isClosedUnmergedPullRequest, isMergedPullRequest, isOpenForgePackageMetadata, isPluginPackageMetadata, isPluginViewKey, isQueuedForMerge, isReadyToMerge, isSupportedOpenForgeApiVersion, makePluginViewKey, parseCheckRuns, parsePluginViewKey, parseStrictFiniteNumber, preservePullRequestState, projectFileTreePathToId, resolveExternalTextFileChunkSize, splitCheckRuns, validateOpenForgePackageMetadata, validatePluginPackageMetadata };
