/* Generated by pnpm build:plugin-sdk-runtime from packages/plugin-sdk/src/index.ts. Do not edit. */
//#region packages/plugin-sdk/src/types.ts
function makePluginViewKey(pluginId, viewId) {
	return `plugin:${pluginId}:${viewId}`;
}
function isPluginViewKey(value) {
	return value.startsWith("plugin:") && value.match(/^plugin:[^:]+:[^:]+$/) !== null;
}
function parsePluginViewKey(key) {
	const parts = key.split(":");
	return {
		pluginId: parts[1],
		viewId: parts[2]
	};
}
var MAX_SUPPORTED_API_VERSION = 1;
//#endregion
//#region packages/plugin-sdk/src/manifest.ts
var contributionSchema = {
	allowedIconKeys: [
		"layout-dashboard",
		"folder-open",
		"git-pull-request",
		"sparkles",
		"settings",
		"terminal",
		"code",
		"file-text",
		"plug",
		"puzzle",
		"boxes",
		"wrench"
	],
	shortcutPattern: "^(?:(?:Cmd|Ctrl|Alt|Shift)\\+)*(?:[a-zA-Z0-9]|F\\d{1,2}|Space|Enter|Tab|Backspace|Escape)$",
	contributionPoints: {
		"views": { "fields": {
			"id": {
				"kind": "nonEmptyString",
				"required": true
			},
			"title": {
				"kind": "nonEmptyString",
				"required": true
			},
			"icon": {
				"kind": "icon",
				"required": true
			},
			"shortcut": { "kind": "shortcut" },
			"railOrder": { "kind": "number" }
		} },
		"taskPaneTabs": { "fields": {
			"id": {
				"kind": "nonEmptyString",
				"required": true
			},
			"title": {
				"kind": "nonEmptyString",
				"required": true
			},
			"icon": { "kind": "icon" },
			"order": { "kind": "number" }
		} },
		"sidebarPanels": { "fields": {
			"id": {
				"kind": "nonEmptyString",
				"required": true
			},
			"title": {
				"kind": "nonEmptyString",
				"required": true
			},
			"side": {
				"kind": "enum",
				"required": true,
				"values": ["left", "right"]
			},
			"order": { "kind": "number" }
		} },
		"commands": { "fields": {
			"id": {
				"kind": "nonEmptyString",
				"required": true
			},
			"title": {
				"kind": "nonEmptyString",
				"required": true
			},
			"shortcut": { "kind": "shortcut" }
		} },
		"settingsSections": { "fields": {
			"id": {
				"kind": "nonEmptyString",
				"required": true
			},
			"title": {
				"kind": "nonEmptyString",
				"required": true
			}
		} },
		"backgroundServices": { "fields": {
			"id": {
				"kind": "nonEmptyString",
				"required": true
			},
			"name": {
				"kind": "nonEmptyString",
				"required": true
			}
		} }
	}
};
var shortcutRegex = new RegExp(contributionSchema.shortcutPattern);
var ALLOWED_ICON_KEYS = new Set(contributionSchema.allowedIconKeys);
function isValidShortcutFormat(shortcut) {
	return shortcutRegex.test(shortcut);
}
function normalizeShortcut(shortcut) {
	let result = "";
	const parts = shortcut.split("+");
	const key = parts[parts.length - 1];
	const modifiers = parts.slice(0, -1);
	if (modifiers.includes("Cmd")) result += "⌘";
	if (modifiers.includes("Ctrl")) result += "⌃";
	if (modifiers.includes("Alt")) result += "⌥";
	if (modifiers.includes("Shift")) result += "⇧";
	result += key.toLowerCase();
	return result;
}
function isString(value) {
	return typeof value === "string";
}
function isNumber(value) {
	return typeof value === "number";
}
function isArray(value) {
	return Array.isArray(value);
}
function isObject(value) {
	return value !== null && typeof value === "object" && !Array.isArray(value);
}
function getRequiredStringError(path) {
	return {
		path,
		message: "Required string"
	};
}
function validateNonEmptyString(value, path, required) {
	if (value === void 0) return required ? [getRequiredStringError(path)] : [];
	if (!isString(value) || !value) return [required ? getRequiredStringError(path) : {
		path,
		message: "Must be a string"
	}];
	return [];
}
function validateIcon(value, path, required) {
	const errors = validateNonEmptyString(value, path, required);
	if (errors.length > 0 || value === void 0) return errors;
	if (!ALLOWED_ICON_KEYS.has(value)) return [{
		path,
		message: `Icon key "${value}" not allowed`
	}];
	return [];
}
function validateNumber(value, path, required) {
	if (value === void 0) return required ? [{
		path,
		message: "Required number"
	}] : [];
	if (!isNumber(value)) return [{
		path,
		message: "Must be a number"
	}];
	return [];
}
function validateShortcut(value, path, required) {
	if (value === void 0) return required ? [getRequiredStringError(path)] : [];
	if (!isString(value)) return [{
		path,
		message: "Must be a string"
	}];
	if (!isValidShortcutFormat(value)) return [{
		path,
		message: "Invalid shortcut format"
	}];
	return [];
}
function validateEnum(value, path, required, values) {
	if (value === void 0) return required ? [getRequiredStringError(path)] : [];
	if (!isString(value) || !values?.includes(value)) return [{
		path,
		message: values === void 0 ? "Invalid value" : `Must be ${values.map((option) => `"${option}"`).join(" or ")}`
	}];
	return [];
}
function validateContributionField(value, path, spec) {
	const required = spec.required === true;
	switch (spec.kind) {
		case "nonEmptyString": return validateNonEmptyString(value, path, required);
		case "icon": return validateIcon(value, path, required);
		case "number": return validateNumber(value, path, required);
		case "shortcut": return validateShortcut(value, path, required);
		case "enum": return validateEnum(value, path, required, spec.values);
	}
}
function validateContributionArray(value, path, spec) {
	const errors = [];
	if (!isArray(value)) {
		errors.push({
			path,
			message: "Must be an array"
		});
		return errors;
	}
	value.forEach((item, index) => {
		const itemPath = `${path}[${index}]`;
		if (!isObject(item)) {
			errors.push({
				path: itemPath,
				message: "Must be an object"
			});
			return;
		}
		Object.entries(spec.fields).forEach(([fieldName, fieldSpec]) => {
			errors.push(...validateContributionField(item[fieldName], `${itemPath}.${fieldName}`, fieldSpec));
		});
	});
	return errors;
}
function validateContributionPoints(contributes) {
	const errors = [];
	if (!isObject(contributes)) {
		errors.push({
			path: "contributes",
			message: "Must be an object"
		});
		return errors;
	}
	Object.entries(contributionSchema.contributionPoints).forEach(([contributionName, contributionSpec]) => {
		const value = contributes[contributionName];
		if (value !== void 0) errors.push(...validateContributionArray(value, `contributes.${contributionName}`, contributionSpec));
	});
	return errors;
}
function validatePluginManifest(data) {
	const errors = [];
	if (!isObject(data)) {
		errors.push({
			path: "",
			message: "Manifest must be an object"
		});
		return errors;
	}
	if (!isString(data.id) || !data.id) errors.push({
		path: "id",
		message: "Required string"
	});
	if (!isString(data.name) || !data.name) errors.push({
		path: "name",
		message: "Required string"
	});
	if (!isString(data.version) || !data.version) errors.push({
		path: "version",
		message: "Required string"
	});
	if (!isNumber(data.apiVersion)) errors.push({
		path: "apiVersion",
		message: "Required number"
	});
	else if (data.apiVersion > 1) errors.push({
		path: "apiVersion",
		message: `API version ${data.apiVersion} not supported (max: 1)`
	});
	if (!isString(data.description) || !data.description) errors.push({
		path: "description",
		message: "Required string"
	});
	if (data.permissions !== void 0 && !isArray(data.permissions)) errors.push({
		path: "permissions",
		message: "Must be an array"
	});
	if (data.contributes !== void 0) errors.push(...validateContributionPoints(data.contributes));
	if (data.frontend === void 0) errors.push({
		path: "frontend",
		message: "Required string or null"
	});
	else if (data.frontend !== null && (!isString(data.frontend) || !data.frontend)) errors.push({
		path: "frontend",
		message: "Must be a non-empty string or null"
	});
	if (data.backend !== void 0 && data.backend !== null && !isString(data.backend)) errors.push({
		path: "backend",
		message: "Must be a string or null"
	});
	return errors;
}
function isPluginManifest(data) {
	return validatePluginManifest(data).length === 0;
}
//#endregion
//#region packages/plugin-sdk/src/context.ts
var PluginContextImpl = class {
	pluginId;
	storage;
	invokeHostFn;
	invokeBackendFn;
	onEventFn;
	constructor(opts) {
		this.pluginId = opts.pluginId;
		this.invokeHostFn = opts.invokeHost;
		this.invokeBackendFn = opts.invokeBackend;
		this.onEventFn = opts.onEvent;
		this.storage = {
			get: (key) => opts.storageGet(key),
			set: (key, value) => opts.storageSet(key, value)
		};
	}
	async invokeHost(command, payload) {
		return this.invokeHostFn(command, payload);
	}
	async invokeBackend(method, payload) {
		return this.invokeBackendFn(method, payload);
	}
	onEvent(event, handler) {
		return this.onEventFn(event, handler);
	}
};
//#endregion
//#region packages/plugin-sdk/src/helpers.ts
function isPluginViewContribution(contribution) {
	return typeof contribution === "object" && contribution !== null && "id" in contribution && "title" in contribution && "icon" in contribution;
}
function isPluginCommandContribution(contribution) {
	return typeof contribution === "object" && contribution !== null && "id" in contribution && "title" in contribution;
}
function getViewContributions(contributes) {
	return contributes?.views ?? [];
}
function getCommandContributions(contributes) {
	return contributes?.commands ?? [];
}
//#endregion
export { ALLOWED_ICON_KEYS, MAX_SUPPORTED_API_VERSION, PluginContextImpl, getCommandContributions, getViewContributions, isPluginCommandContribution, isPluginManifest, isPluginViewContribution, isPluginViewKey, isValidShortcutFormat, makePluginViewKey, normalizeShortcut, parsePluginViewKey, validatePluginManifest };
