export {
  acquire,
  attach,
  clearPtySpawnPending,
  clearTaskTerminalTabsSession,
  detach,
  focusTerminal,
  getShellLifecycleState,
  getTaskTerminalTabsSession,
  isPtyActive,
  isValidTerminalDimensions,
  markPtySpawnPending,
  recoverActiveTerminal,
  release,
  releaseAllForTask,
  setCurrentPtyInstance,
  shouldSpawnPty,
  updateShellLifecycleState,
  updateTaskTerminalTabsSession,
  type PoolEntry,
  type ShellLifecycleState,
  type TaskTerminalTabsSession,
  type TerminalTab,
} from '../../../src/lib/terminalPool'
