#!/usr/bin/env node
import { mkdir, rm } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build as viteBuild } from 'vite'
import { buildPluginSdkRuntime } from './build-plugin-sdk-runtime.mjs'

function repoRoot() {
  return resolve(dirname(fileURLToPath(import.meta.url)), '..')
}

export const HOST_RUNTIME_RESOURCE_DIR = 'plugin-host'
const BACKEND_PLUGIN_HOST_BANNER = '/* Generated by pnpm electron:build from src-tauri/plugin-host/index.ts. Do not edit. */'
export const SVELTE_HOST_RUNTIME_ENTRIES = Object.freeze({
  index: 'index-client.js',
  animate: 'animate/index.js',
  attachments: 'attachments/index.js',
  easing: 'easing/index.js',
  events: 'events/index.js',
  internal: 'internal/index.js',
  'internal/client/index': 'internal/client/index.js',
  'internal/disclose-version': 'internal/disclose-version.js',
  'internal/flags/async': 'internal/flags/async.js',
  'internal/flags/legacy': 'internal/flags/legacy.js',
  'internal/flags/tracing': 'internal/flags/tracing.js',
  legacy: 'legacy/legacy-client.js',
  motion: 'motion/index.js',
  reactivity: 'reactivity/index-client.js',
  'reactivity/window/index': 'reactivity/window/index.js',
  store: 'store/index-client.js',
  transition: 'transition/index.js',
})

export function svelteHostRuntimeSpecifierForEntry(entryName) {
  const publicName = entryName.replace(/\/index$/, '')
  return publicName === 'index' ? 'svelte' : `svelte/${publicName}`
}

export function svelteHostRuntimeAssetPathForEntry(entryName) {
  return `${entryName}.js`
}

export function svelteHostRuntimeImportMapEntries() {
  return Object.fromEntries(
    Object.keys(SVELTE_HOST_RUNTIME_ENTRIES).map(entryName => [
      svelteHostRuntimeSpecifierForEntry(entryName),
      `plugin://host-runtime/svelte/${svelteHostRuntimeAssetPathForEntry(entryName)}`,
    ]),
  )
}

export async function buildBackendPluginHostRuntime(root = repoRoot(), outDir = resolve(root, 'dist-electron', HOST_RUNTIME_RESOURCE_DIR)) {
  await viteBuild({
    configFile: false,
    root,
    publicDir: false,
    logLevel: 'info',
    resolve: {
      alias: {
        '@openforge/plugin-runtime/commandValidation': resolve(root, 'packages', 'plugin-runtime', 'src', 'commandValidation.ts'),
        '@openforge/plugin-runtime': resolve(root, 'packages', 'plugin-runtime', 'src', 'index.ts'),
      },
    },
    build: {
      emptyOutDir: false,
      lib: {
        entry: resolve(root, 'src-tauri', 'plugin-host', 'index.ts'),
        formats: ['es'],
        fileName: () => 'index.js',
      },
      minify: false,
      outDir,
      sourcemap: false,
      target: 'es2022',
      rollupOptions: {
        external: id => id.startsWith('node:'),
        output: {
          banner: BACKEND_PLUGIN_HOST_BANNER,
        },
      },
    },
  })

  return resolve(outDir, 'index.js')
}

export async function copyHostRuntimeAssets(root = repoRoot(), electronDist = resolve(root, 'dist-electron')) {
  const hostRuntimeDir = resolve(electronDist, HOST_RUNTIME_RESOURCE_DIR)
  await rm(hostRuntimeDir, { recursive: true, force: true })
  await mkdir(hostRuntimeDir, { recursive: true })
  await buildPluginSdkRuntime({
    workspaceRoot: root,
    outDir: resolve(hostRuntimeDir, 'plugin-sdk'),
  })
  await buildBackendPluginHostRuntime(root, hostRuntimeDir)
  await buildSvelteHostRuntimeAssets(root, resolve(hostRuntimeDir, 'svelte'))
}

export async function buildSvelteHostRuntimeAssets(root = repoRoot(), outDir = resolve(root, 'dist-electron', HOST_RUNTIME_RESOURCE_DIR, 'svelte')) {
  const svelteSrcDir = resolve(root, 'node_modules', 'svelte', 'src')
  const entry = Object.fromEntries(
    Object.entries(SVELTE_HOST_RUNTIME_ENTRIES).map(([name, relPath]) => [name, resolve(svelteSrcDir, relPath)]),
  )

  await viteBuild({
    configFile: false,
    root,
    publicDir: false,
    logLevel: 'info',
    build: {
      emptyOutDir: true,
      lib: {
        entry,
        formats: ['es'],
      },
      minify: false,
      outDir,
      sourcemap: false,
      target: 'es2022',
      rollupOptions: {
        output: {
          entryFileNames: '[name].js',
          chunkFileNames: 'chunks/[name]-[hash].js',
        },
      },
    },
  })
}

function waitForExit(child, label) {
  return new Promise((resolvePromise, reject) => {
    child.once('error', reject)
    child.once('exit', (code, signal) => {
      if (code === 0) {
        resolvePromise()
        return
      }
      reject(new Error(`${label} exited with ${signal ?? `code ${code}`}`))
    })
  })
}

async function main() {
  await rm(resolve(repoRoot(), 'dist-electron'), { recursive: true, force: true })
  const root = repoRoot()
  await waitForExit(spawn('tsc', ['-p', 'tsconfig.electron.json'], {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  }), 'tsc -p tsconfig.electron.json')
  await copyHostRuntimeAssets(root)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(error => {
    console.error(error instanceof Error ? error.message : error)
    process.exit(1)
  })
}
