#!/usr/bin/env node
import { copyFile, mkdir, rm } from 'node:fs/promises'
import { spawn } from 'node:child_process'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build as viteBuild } from 'vite'
import { buildPluginSdkRuntime } from './build-plugin-sdk-runtime.mjs'
import { buildTerminalRuntime } from './build-terminal-runtime.mjs'
import { resolveRustSidecarLayout } from './rust-sidecar-layout.mjs'
import {
  svelteHostRuntimeBuildEntries,
  svelteHostRuntimeImportMapEntries,
} from '../packages/plugin-sdk/src/svelteHostRuntimeContract.mjs'

function repoRoot() {
  return resolve(dirname(fileURLToPath(import.meta.url)), '..')
}

export const HOST_RUNTIME_RESOURCE_DIR = 'plugin-host'
function backendPluginHostBanner(rustSidecarLayout) {
  return `/* Generated by pnpm electron:build from ${rustSidecarLayout.backendCrateRoot}/plugin-host/index.ts. Do not edit. */`
}
export const SVELTE_HOST_RUNTIME_ENTRIES = Object.freeze(svelteHostRuntimeBuildEntries())
export { svelteHostRuntimeImportMapEntries }

export async function buildBackendPluginHostRuntime(root = repoRoot(), outDir = resolve(root, 'dist-electron', HOST_RUNTIME_RESOURCE_DIR), rustSidecarLayout = resolveRustSidecarLayout({ repoRoot: root })) {
  await viteBuild({
    configFile: false,
    root,
    publicDir: false,
    logLevel: 'info',
    resolve: {
      alias: {
        '@openforge/plugin-runtime/commandValidation': resolve(root, 'packages', 'plugin-runtime', 'src', 'commandValidation.ts'),
        '@openforge/plugin-runtime': resolve(root, 'packages', 'plugin-runtime', 'src', 'index.ts'),
      },
    },
    build: {
      emptyOutDir: false,
      lib: {
        entry: resolve(rustSidecarLayout.backendCrateRootPath, 'plugin-host', 'index.ts'),
        formats: ['es'],
        fileName: () => 'index.js',
      },
      minify: false,
      outDir,
      sourcemap: false,
      target: 'es2022',
      rollupOptions: {
        external: id => id.startsWith('node:'),
        output: {
          banner: backendPluginHostBanner(rustSidecarLayout),
        },
      },
    },
  })

  return resolve(outDir, 'index.js')
}

export async function copyElectronMainRuntimeAssets(root = repoRoot(), electronDist = resolve(root, 'dist-electron')) {
  await copyFile(
    resolve(root, 'packages', 'plugin-sdk', 'src', 'svelteHostRuntimeContract.mjs'),
    resolve(electronDist, 'svelteHostRuntimeContract.mjs'),
  )
  await copyFile(
    resolve(root, 'src', 'electron', 'preloadBridge.cjs'),
    resolve(electronDist, 'preloadBridge.cjs'),
  )
}

export async function copyHostRuntimeAssets(root = repoRoot(), electronDist = resolve(root, 'dist-electron')) {
  const hostRuntimeDir = resolve(electronDist, HOST_RUNTIME_RESOURCE_DIR)
  await rm(hostRuntimeDir, { recursive: true, force: true })
  await mkdir(hostRuntimeDir, { recursive: true })
  await buildPluginSdkRuntime({
    workspaceRoot: root,
    outDir: resolve(hostRuntimeDir, 'plugin-sdk'),
  })
  await buildTerminalRuntime({
    workspaceRoot: root,
    outDir: resolve(hostRuntimeDir, 'terminal-runtime'),
  })
  await buildBackendPluginHostRuntime(root, hostRuntimeDir)
  await buildSvelteHostRuntimeAssets(root, resolve(hostRuntimeDir, 'svelte'))
}

export async function buildSvelteHostRuntimeAssets(root = repoRoot(), outDir = resolve(root, 'dist-electron', HOST_RUNTIME_RESOURCE_DIR, 'svelte')) {
  const svelteSrcDir = resolve(root, 'node_modules', 'svelte', 'src')
  const entry = Object.fromEntries(
    Object.entries(SVELTE_HOST_RUNTIME_ENTRIES).map(([name, relPath]) => [name, resolve(svelteSrcDir, relPath)]),
  )

  await viteBuild({
    configFile: false,
    root,
    publicDir: false,
    logLevel: 'info',
    build: {
      emptyOutDir: true,
      lib: {
        entry,
        formats: ['es'],
      },
      minify: false,
      outDir,
      sourcemap: false,
      target: 'es2022',
      rollupOptions: {
        output: {
          entryFileNames: '[name].js',
          chunkFileNames: 'chunks/[name]-[hash].js',
        },
      },
    },
  })
}

function waitForExit(child, label) {
  return new Promise((resolvePromise, reject) => {
    child.once('error', reject)
    child.once('exit', (code, signal) => {
      if (code === 0) {
        resolvePromise()
        return
      }
      reject(new Error(`${label} exited with ${signal ?? `code ${code}`}`))
    })
  })
}

async function main() {
  await rm(resolve(repoRoot(), 'dist-electron'), { recursive: true, force: true })
  const root = repoRoot()
  await waitForExit(spawn('tsc', ['-p', 'tsconfig.electron.json'], {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  }), 'tsc -p tsconfig.electron.json')
  await copyElectronMainRuntimeAssets(root)
  await copyHostRuntimeAssets(root)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(error => {
    console.error(error instanceof Error ? error.message : error)
    process.exit(1)
  })
}
