export {
  APP_EVENTS_RECONNECTED_EVENT,
  createTerminalRuntime,
  ptyExitEventName,
  ptyOutputEventName,
  terminalModelOutputEventName,
  terminalModelDisabledEventName,
  type AppEventsReconnectedPayload,
  type PoolEntry,
  type PtyBufferState,
  type PtyExitEventPayload,
  type PtyOutputEventPayload,
  type TerminalModelDisabledEventPayload,
  type TerminalModelOutputEventPayload,
  type TerminalStateSource,
  type TerminalViewSnapshot,
  type TerminalView,
  type TerminalViewData,
  type TerminalViewLiveOutput,
  type TerminalViewDisposable,
  type TerminalViewFactory,
  type TerminalViewFactoryOptions,
  type TerminalViewGeometry,
  type TerminalViewRendererFailure,
  type TerminalViewTheme,
  type ShellLifecycleState,
  type TaskTerminalTabsSession,
  type TerminalRuntime,
  type TerminalRuntimeEvent,
  type TerminalRuntimeEventName,
  type TerminalRuntimeEventPayload,
  type TerminalRuntimeHost,
  type TerminalImageProtocol,
  type TerminalRuntimeUnlistenFn,
  type TerminalTab,
} from './terminalRuntime'
export {
  TERMINAL_CELL_HEIGHT,
  TERMINAL_FONT_FAMILY,
  TERMINAL_FONT_SIZE,
  TERMINAL_WEB_FONT_FACES,
  getTerminalOptions,
  preloadTerminalFonts,
} from './terminalOptions'
export {
  getTerminalTheme,
  setupHostThemeSync,
  syncThemeModeWithDocument,
  themeMode,
  type ThemeMode,
} from './theme'
export {
  handleTerminalShortcutKeydown,
  type TerminalShortcutController,
} from './terminalShortcuts'
export {
  createTerminalShortcutController,
  isTerminalShortcutScopeVisible,
  type TerminalShortcutControllerOptions,
  type TerminalShortcutControllerWiring,
  type TerminalShortcutKeydownTarget,
  type TerminalTabsShortcutTarget,
} from './terminalShortcutController'
export {
  createLoadingTerminalTaskPaneWorkspaceSnapshot,
  createRejectedTerminalTaskPaneWorkspaceSnapshot,
  createResolvedTerminalTaskPaneWorkspaceSnapshot,
  createTerminalTaskPaneWorkspaceLookupController,
  formatTerminalTaskPaneWorkspaceLookupError,
  getTerminalTaskPaneWorkspaceStatusText,
  type TerminalTaskPaneTaskSwitch,
  type TerminalTaskPaneWorkspaceLookupController,
  type TerminalTaskPaneWorkspaceLookupRequest,
  type TerminalTaskPaneWorkspaceLookupState,
  type TerminalTaskPaneWorkspaceResult,
  type TerminalTaskPaneWorkspaceSnapshot,
} from './taskPaneWorkspaceLookup'
export {
  createTaskTerminalPaneLifecycle,
  type TaskTerminalPaneLifecycle,
  type TaskTerminalPaneLifecycleOptions,
  type TerminalTaskPaneController,
} from './taskTerminalPaneLifecycle'
export {
  TERMINAL_FOCUS_DESCRIPTION_TEXT,
  TERMINAL_TASK_PANE_KEYBOARD_FOCUS_PATH_TEXT,
  TERMINAL_TASK_PANE_WORKSPACE_RECOVERY_TEXT,
  createTerminalTabsController,
  getRestartShellAriaLabel,
  getRestartShellTitle,
  getShellLabel,
  getTerminalFocusDescriptionId,
  getTerminalRegionAriaLabel,
  getTerminalRegionTitle,
  getTerminalTabAccessibleLabel,
  getTerminalTabPanelId,
  getTerminalTabStatus,
  getTerminalTabTriggerId,
  isTerminalTabExited,
  shouldShowShellReadyAffordance,
  type CloseTerminalTabOptions,
  type TerminalTabsController,
  type TerminalTabsControllerOptions,
  type TerminalTabsControllerSnapshot,
} from './terminalControls'
