import type {
  BackendFileSystemAPI,
  BackendMethodRegistration,
  BackendMethodRegistry,
  BackendOpenForgeAPI,
  BackendPlugin,
  BackendPluginContext,
  BackgroundServiceRegistration,
  BackgroundServiceRegistry,
  CommandDescriptor,
  CommandRegistry,
  CommandRegistration,
  CommandShortcutMetadata,
  Disposable,
  ExternalReadDirectoryRequest,
  ExternalReadFileRequest,
  ExternalReadFileSystemAPI,
  UserDataDirectoryRequest,
  UserDataFileRequest,
  UserDataFileSystemAPI,
  UserDataFileWriteRequest,
  NavigationAPI,
  OpenForgeContextSnapshot,
  OpenForgeNavigationRequest,
  OpenForgeNavigationSnapshot,
} from './types'

export function defineBackendPlugin<const TPlugin extends BackendPlugin>(plugin: TPlugin): TPlugin {
  return plugin
}

export type {
  BackendFileSystemAPI,
  BackendMethodRegistration,
  BackendMethodRegistry,
  BackendOpenForgeAPI,
  BackendPlugin,
  BackendPluginContext,
  BackgroundServiceRegistration,
  BackgroundServiceRegistry,
  CommandDescriptor,
  CommandRegistry,
  CommandRegistration,
  CommandShortcutMetadata,
  Disposable,
  ExternalReadDirectoryRequest,
  ExternalReadFileRequest,
  ExternalReadFileSystemAPI,
  UserDataDirectoryRequest,
  UserDataFileRequest,
  UserDataFileSystemAPI,
  UserDataFileWriteRequest,
  NavigationAPI,
  OpenForgeContextSnapshot,
  OpenForgeNavigationRequest,
  OpenForgeNavigationSnapshot,
}
