import type {
  BrowserSurfaceCapture,
  BrowserDevToolsPanel,
  BrowserSurfaceFeedbackSelection,
  BrowserSurfaceVisualFeedback,
  BrowserSurfaceRegion,
  BrowserSurfaceErrorCode,
  BrowserSurfaceNavigationError,
  BrowserSurfacesAPI,
  GetOrCreateBrowserSurfaceRequest,
  TaskBrowserSurfaceController,
  TaskBrowserSurfaceState,
} from './browserSurfaces.js'
import type {
  CommandDescriptor,
  CommandRegistry,
  CommandRegistration,
  CommandShortcutMetadata,
  ComposeTaskRequest,
  ComposeTaskResult,
  Disposable,
  FrontendBackendBridge,
  FrontendOpenForgeAPI,
  FrontendPlugin,
  FrontendPluginContext,
  FrontendSettingsRegistry,
  FrontendTaskPaneRegistry,
  FrontendInjectionPointRegistry,
  FrontendTaskStartRegistry,
  FrontendReviewUIRegistry,
  FrontendTaskUIRegistry,
  FrontendViewRegistry,
  FrontendViewReplacementRegistry,
  InjectionPointLocation,
  NavigationAPI,
  OpenForgeContextChangeHandler,
  OpenForgeContextSnapshot,
  OpenForgeNavigationRequest,
  OpenForgeNavigationSnapshot,
  PluginIcon,
  PluginSidebarNavigationProps,
  PluginSidebarViewIdentity,
  PluginInjectionPointProps,
  PluginInjectionPointRegistration,
  PluginSettingsSectionProps,
  PluginSettingsSectionRegistration,
  PluginSettingsSectionScope,
  PluginStorageScope,
  PluginSvgIcon,
  PluginTaskPaneProps,
  PluginTaskPaneTabRegistration,
  PluginReviewRowActionProps,
  PluginReviewRowActionRegistration,
  PluginTaskUISectionProps,
  PluginTaskUISectionRegistration,
  PluginViewProps,
  PluginViewRegistration,
  PluginProjectDashboardReplacementProps,
  PluginProjectDashboardReplacementRegistration,
  PluginViewReplacementRegistration,
  ReplaceableViewTarget,
  TaskStartPrefixContext,
  TaskStartPrefixProviderRegistration,
  PtyBufferState,
  TerminalImageProtocol,
  TerminalViewSnapshot,
} from './types.js'

export const OPENFORGE_FRONTEND_PLUGIN_MARKER = '__openforgeFrontendPlugin'

export type MarkedFrontendPlugin<TPlugin extends FrontendPlugin = FrontendPlugin> = TPlugin & {
  readonly [OPENFORGE_FRONTEND_PLUGIN_MARKER]: true
}

export function defineFrontendPlugin<const TPlugin extends FrontendPlugin>(plugin: TPlugin): MarkedFrontendPlugin<TPlugin> {
  Object.defineProperty(plugin, OPENFORGE_FRONTEND_PLUGIN_MARKER, {
    value: true,
    enumerable: false,
    configurable: false,
  })
  return plugin as MarkedFrontendPlugin<TPlugin>
}

export { BrowserSurfaceError, isAllowedBrowserSurfaceUrl } from './browserSurfaces.js'

export type {
  BrowserSurfaceCapture,
  BrowserDevToolsPanel,
  BrowserSurfaceFeedbackSelection,
  BrowserSurfaceVisualFeedback,
  BrowserSurfaceRegion,
  BrowserSurfaceErrorCode,
  BrowserSurfaceNavigationError,
  BrowserSurfacesAPI,
  GetOrCreateBrowserSurfaceRequest,
  TaskBrowserSurfaceController,
  TaskBrowserSurfaceState,
}

export type {
  CommandDescriptor,
  CommandRegistry,
  CommandRegistration,
  CommandShortcutMetadata,
  ComposeTaskRequest,
  ComposeTaskResult,
  Disposable,
  FrontendBackendBridge,
  FrontendOpenForgeAPI,
  FrontendPlugin,
  FrontendPluginContext,
  FrontendSettingsRegistry,
  FrontendTaskPaneRegistry,
  FrontendInjectionPointRegistry,
  FrontendTaskStartRegistry,
  FrontendReviewUIRegistry,
  FrontendTaskUIRegistry,
  FrontendViewRegistry,
  FrontendViewReplacementRegistry,
  InjectionPointLocation,
  NavigationAPI,
  OpenForgeContextChangeHandler,
  OpenForgeContextSnapshot,
  OpenForgeNavigationRequest,
  OpenForgeNavigationSnapshot,
  PluginIcon,
  PluginSidebarNavigationProps,
  PluginSidebarViewIdentity,
  PluginInjectionPointProps,
  PluginInjectionPointRegistration,
  PluginSettingsSectionProps,
  PluginSettingsSectionRegistration,
  PluginSettingsSectionScope,
  PluginStorageScope,
  PluginSvgIcon,
  PluginTaskPaneProps,
  PluginTaskPaneTabRegistration,
  PluginReviewRowActionProps,
  PluginReviewRowActionRegistration,
  PluginTaskUISectionProps,
  PluginTaskUISectionRegistration,
  PluginViewProps,
  PluginViewRegistration,
  PluginProjectDashboardReplacementProps,
  PluginProjectDashboardReplacementRegistration,
  PluginViewReplacementRegistration,
  ReplaceableViewTarget,
  TaskStartPrefixContext,
  TaskStartPrefixProviderRegistration,
  PtyBufferState,
  TerminalImageProtocol,
  TerminalViewSnapshot,
}
