export {
  OPENFORGE_PACKAGE_METADATA_SCHEMA,
  OPENFORGE_PLUGIN_CAPABILITIES,
  isOpenForgePackageMetadata,
  isPluginPackageMetadata,
  isSupportedOpenForgeApiVersion,
  validateOpenForgePackageMetadata,
  validatePluginPackageMetadata,
} from './manifest'

export {
  createMemoryPluginStorage,
  createMockBackendOpenForgeApi,
  createMockFrontendOpenForgeApi,
  createMockOpenForgeApi,
  createMockPluginContext,
  createOpenForgeRegistryFake,
  createTestingCalls,
  TestingOpenForgeRegistryFake,
  TestingSubscriptionSink,
} from './testing'

export {
  MAX_SUPPORTED_API_VERSION,
  MIN_SUPPORTED_API_VERSION,
  OPENFORGE_PLUGIN_API_VERSION,
  SUPPORTED_OPENFORGE_API_VERSIONS,
  isPluginViewKey,
  makePluginViewKey,
  parsePluginViewKey,
} from './types'

export type {
  AttentionAPI,
  BackendReadyState,
  CommandDescriptor,
  CommandRegistry,
  CommandRegistration,
  CommandShortcutMetadata,
  ConfigureStartPromptContributionRequest,
  CreateTaskRequest,
  Disposable,
  FileSystemAPI,
  ImplementationRun,
  InjectionPointLocation,
  JsonObject,
  JsonPrimitive,
  JsonSchema,
  JsonValue,
  MaybePromise,
  KeyValueConfigAPI,
  NotificationRequest,
  NavigationAPI,
  NotificationsAPI,
  OpenForgeCommonAPI,
  OpenForgeContextSnapshot,
  OpenForgeNavigationRequest,
  OpenForgeNavigationSnapshot,
  OpenForgePackageMetadata,
  OpenForgePluginCapability,
  OpenForgePluginContext,
  OpenForgePluginPackageJson,
  PluginComponentLoader,
  PluginComponentModule,
  PluginEntry,
  PluginIcon,
  PluginInjectionPointProps,
  PluginSettingsSectionProps,
  PluginState,
  PluginSvgIcon,
  PluginTaskPaneProps,
  PluginTaskUISectionProps,
  PluginViewProps,
  PluginStorage,
  PluginStorageScope,
  PluginViewKey,
  ProjectsAPI,
  ShellAPI,
  ShellResizeRequest,
  ShellSessionRequest,
  ShellSpawnRequest,
  ShellWriteRequest,
  StartPromptContribution,
  StartTaskImplementationRequest,
  SubscriptionSink,
  SupportedOpenForgeApiVersion,
  SystemAPI,
  TasksAPI,
  ValidationError,
} from './types'

export type {
  MockBackendOpenForgeAPI,
  MockFrontendOpenForgeAPI,
  TestingBackgroundServiceContribution,
  TestingBackendMethodContribution,
  TestingCommandContribution,
  TestingContributionBase,
  TestingEventListenerContribution,
  TestingOpenForgeApiCalls,
  TestingOpenForgeApiOptions,
  TestingOpenForgeRegistrySnapshot,
  TestingRuntimeKind,
  TestingRuntimeScope,
  TestingSettingsSectionContribution,
  TestingTaskPaneTabContribution,
  TestingTaskUISectionContribution,
  TestingViewContribution,
} from './testing'

export { parseStrictFiniteNumber } from './numberParsing'
export {
  buildProjectFileTree,
  flattenVisibleProjectFileTree,
  formatProjectFileTreeSize,
  getProjectFileTreeDepth,
  getProjectFileTreeItemAccessibility,
  getProjectFileTreeKeyboardAction,
  getProjectFileTreeParentPath,
  hasProjectFileTreeShortcutModifier,
  projectFileTreePathToId,
} from './projectFileTree'
export type {
  ProjectFileTreeEntry,
  ProjectFileTreeItemAccessibility,
  ProjectFileTreeKeyboardAction,
  ProjectFileTreeNode,
} from './projectFileTree'
export {
  canMergePullRequest,
  getMergeReadiness,
  hasMergeConflicts,
  isClosedUnmergedPullRequest,
  isMergedPullRequest,
  isQueuedForMerge,
  isReadyToMerge,
  parseCheckRuns,
  preservePullRequestState,
  splitCheckRuns,
} from './domain'
export type * from './domain'
