export { BrowserSurfaceError, isAllowedBrowserSurfaceUrl } from './browserSurfaces'
export type {
  BrowserSurfaceCapture,
  BrowserSurfaceFeedbackSelection,
  BrowserSurfaceVisualFeedback,
  BrowserSurfaceRegion,
  BrowserSurfaceErrorCode,
  BrowserSurfaceNavigationError,
  BrowserSurfacesAPI,
  GetOrCreateBrowserSurfaceRequest,
  TaskBrowserSurfaceController,
  TaskBrowserSurfaceState,
} from './browserSurfaces'

export {
  OPENFORGE_PACKAGE_METADATA_SCHEMA,
  OPENFORGE_PLUGIN_CAPABILITIES,
  isOpenForgePackageMetadata,
  isPluginPackageMetadata,
  isSupportedOpenForgeApiVersion,
  validateOpenForgePackageMetadata,
  validatePluginPackageMetadata,
} from './manifest'

export {
  createMemoryPluginStorage,
  createMockBackendOpenForgeApi,
  createMockFrontendOpenForgeApi,
  createMockOpenForgeApi,
  createMockPluginContext,
  createOpenForgeRegistryFake,
  createTestingCalls,
  TestingOpenForgeRegistryFake,
  TestingSubscriptionSink,
} from './testing'

export {
  DEFAULT_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES,
  MAX_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES,
  MIN_EXTERNAL_TEXT_FILE_CHUNK_SIZE_BYTES,
  TaskFollowUpError,
  MAX_SUPPORTED_API_VERSION,
  MIN_SUPPORTED_API_VERSION,
  OPENFORGE_PLUGIN_API_VERSION,
  SUPPORTED_OPENFORGE_API_VERSIONS,
  isPluginViewKey,
  resolveExternalTextFileChunkSize,
  makePluginViewKey,
  parsePluginViewKey,
} from './types'

export type {
  AgentCommandDescriptor,
  AgentCommandMetadata,
  AgentCommandRuntime,
  AttentionAPI,
  BackendReadyState,
  CommandDescriptor,
  CommandRegistry,
  CommandRegistration,
  CommandShortcutMetadata,
  ComposeTaskRequest,
  ComposeTaskResult,
  ConfigureStartPromptContributionRequest,
  CreateTaskRequest,
  Disposable,
  BackendFileSystemAPI,
  ExternalFileMetadata,
  ExternalReadDirectoryRequest,
  ExternalReadFileRequest,
  ExternalReadTextFileChunksRequest,
  ExternalReadFileSystemAPI,
  FileSystemAPI,
  UserDataDirectoryRequest,
  UserDataFileAppendResult,
  UserDataFileRequest,
  UserDataFileSystemAPI,
  UserDataFileWriteRequest,
  ImplementationRun,
  ListTaskSessionsRequest,
  InjectionPointLocation,
  JsonObject,
  JsonPrimitive,
  JsonSchema,
  JsonValue,
  MaybePromise,
  KeyValueConfigAPI,
  NotificationRequest,
  NavigationAPI,
  NotificationsAPI,
  OpenForgeCommonAPI,
  OpenForgeContextChangeHandler,
  OpenForgeContextSnapshot,
  OpenForgeNavigationRequest,
  OpenForgeNavigationSnapshot,
  OpenForgePackageMetadata,
  OpenForgePluginCapability,
  OpenForgePluginContext,
  OpenForgePluginPackageJson,
  PluginCommandInvocationContext,
  PluginCommandInvocationSource,
  PluginComponentLoader,
  PluginComponentModule,
  PluginEntry,
  PluginIcon,
  PluginSidebarNavigationProps,
  PluginSidebarViewIdentity,
  PluginInjectionPointProps,
  PluginSettingsSectionProps,
  PluginState,
  PluginSvgIcon,
  PluginTaskPaneProps,
  PluginTaskUISectionProps,
  PluginViewProps,
  PluginStorage,
  PluginStorageScope,
  PluginViewKey,
  ProjectsAPI,
  PtyBufferState,
  ShellAPI,
  ShellResizeRequest,
  TaskStartPrefixContext,
  TaskStartPrefixProviderRegistration,
  TerminalImageProtocol,
  TerminalViewSnapshot,
  ShellSessionRequest,
  ShellSpawnRequest,
  ShellWriteRequest,
  StartPromptContribution,
  SendTaskFollowUpRequest,
  StartTaskImplementationRequest,
  TaskFollowUpDisposition,
  TaskFollowUpErrorCode,
  TaskFollowUpReceipt,
  SubscriptionSink,
  SupportedOpenForgeApiVersion,
  SystemAPI,
  TasksAPI,
  ValidationError,
} from './types'

export type {
  MockBackendOpenForgeAPI,
  MockFrontendOpenForgeAPI,
  TestingBackgroundServiceContribution,
  TestingBackendMethodContribution,
  TestingCommandContribution,
  TestingContributionBase,
  TestingExternalTextFile,
  TestingExternalTextFileChunksCall,
  TestingEventListenerContribution,
  TestingOpenForgeApiCalls,
  TestingOpenForgeApiOptions,
  TestingOpenForgeRegistrySnapshot,
  TestingRuntimeKind,
  TestingRuntimeScope,
  TestingSettingsSectionContribution,
  TestingTaskPaneTabContribution,
  TestingTaskUISectionContribution,
  TestingViewContribution,
} from './testing'

export { parseStrictFiniteNumber } from './numberParsing'
export {
  buildProjectFileTree,
  flattenVisibleProjectFileTree,
  formatProjectFileTreeSize,
  getProjectFileTreeDepth,
  getProjectFileTreeItemAccessibility,
  getProjectFileTreeKeyboardAction,
  getProjectFileTreeParentPath,
  hasProjectFileTreeShortcutModifier,
  projectFileTreePathToId,
} from './projectFileTree'
export type {
  ProjectFileTreeEntry,
  ProjectFileTreeItemAccessibility,
  ProjectFileTreeKeyboardAction,
  ProjectFileTreeNode,
} from './projectFileTree'
export {
  canMergePullRequest,
  getMergeReadiness,
  hasMergeConflicts,
  isClosedUnmergedPullRequest,
  isMergedPullRequest,
  isQueuedForMerge,
  isReadyToMerge,
  parseCheckRuns,
  preservePullRequestState,
  splitCheckRuns,
} from './domain'
export type * from './domain'
