use std::fs;
use std::path::{Path, PathBuf};

pub(crate) const OPENFORGE_CODEX_PROFILE_NAME: &str = "openforge-lifecycle";
const OPENFORGE_CODEX_SANDBOX_MODE: &str = "danger-full-access";
const OPENFORGE_CODEX_APPROVAL_POLICY: &str = "never";
const CODEX_HOOK_SOURCE: &str = include_str!("codex-hooks/openforge-hook.js");

fn codex_home_from(codex_home: Option<&Path>, home_dir: Option<&Path>) -> Option<PathBuf> {
    codex_home
        .filter(|path| !path.as_os_str().is_empty())
        .map(PathBuf::from)
        .or_else(|| home_dir.map(|home| home.join(".codex")))
}

fn codex_home_dir() -> Option<PathBuf> {
    let codex_home = std::env::var_os("CODEX_HOME")
        .filter(|path| !path.is_empty())
        .map(PathBuf::from);
    codex_home_from(codex_home.as_deref(), dirs::home_dir().as_deref())
}

fn codex_hooks_profile_path_for_home(codex_home: &Path) -> PathBuf {
    codex_home.join(format!("{OPENFORGE_CODEX_PROFILE_NAME}.config.toml"))
}

pub(crate) fn ensure_codex_hooks_installed() -> Result<PathBuf, Box<dyn std::error::Error>> {
    let codex_home = codex_home_dir().ok_or("could not determine Codex home directory")?;
    let install_dir = codex_home.join("openforge");
    fs::create_dir_all(&install_dir)?;

    let hook_path = install_dir.join("openforge-hook.js");
    fs::write(&hook_path, CODEX_HOOK_SOURCE)?;

    let profile_path = codex_hooks_profile_path_for_home(&codex_home);
    fs::write(&profile_path, render_codex_hooks_profile(&hook_path))?;

    Ok(profile_path)
}

fn render_codex_hooks_profile(hook_script_path: &Path) -> String {
    let mut profile =
        "# Generated by OpenForge. Codex may require /hooks trust review before these run.\n\n"
            .to_string();
    profile.push_str(&format!(
        "sandbox_mode = \"{}\"\napproval_policy = \"{}\"\n\n",
        toml_basic_string(OPENFORGE_CODEX_SANDBOX_MODE),
        toml_basic_string(OPENFORGE_CODEX_APPROVAL_POLICY),
    ));

    append_hook(
        &mut profile,
        hook_script_path,
        "SessionStart",
        Some("startup|resume|clear|compact"),
        "started",
    );
    append_hook(
        &mut profile,
        hook_script_path,
        "UserPromptSubmit",
        None,
        "became_busy",
    );
    append_hook(
        &mut profile,
        hook_script_path,
        "PreToolUse",
        Some("*"),
        "became_busy",
    );
    append_hook(
        &mut profile,
        hook_script_path,
        "PostToolUse",
        Some("*"),
        "became_busy",
    );
    append_hook(
        &mut profile,
        hook_script_path,
        "PermissionRequest",
        Some("*"),
        "requested_permission",
    );
    append_hook(&mut profile, hook_script_path, "Stop", None, "ended");

    profile
}

fn append_hook(
    profile: &mut String,
    hook_script_path: &Path,
    event: &str,
    matcher: Option<&str>,
    kind: &str,
) {
    profile.push_str(&format!("[[hooks.{event}]]\n"));
    if let Some(matcher) = matcher {
        profile.push_str(&format!("matcher = \"{}\"\n", toml_basic_string(matcher)));
    }
    profile.push_str(&format!("[[hooks.{event}.hooks]]\n"));
    profile.push_str("type = \"command\"\n");
    profile.push_str(&format!(
        "command = \"{}\"\n",
        toml_basic_string(&hook_command(hook_script_path, kind, event))
    ));
    profile.push_str("timeout = 10\n");
    profile.push_str("statusMessage = \"Reporting OpenForge lifecycle\"\n\n");
}

fn hook_command(hook_script_path: &Path, kind: &str, event: &str) -> String {
    format!(
        "node \"{}\" {kind} {event}",
        shell_double_quote_inner(&hook_script_path.to_string_lossy())
    )
}

fn shell_double_quote_inner(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
        .replace('`', "\\`")
}

fn toml_basic_string(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn codex_hook_reports_richer_lifecycle_events_to_openforge_hook() {
        assert!(CODEX_HOOK_SOURCE.contains("OPENFORGE_TASK_ID"));
        assert!(CODEX_HOOK_SOURCE.contains("OPENFORGE_PTY_INSTANCE_ID"));
        assert!(CODEX_HOOK_SOURCE.contains("OPENFORGE_HTTP_PORT"));
        assert!(CODEX_HOOK_SOURCE.contains("/hooks/agent-lifecycle"));
        assert!(CODEX_HOOK_SOURCE.contains("provider: \"codex\""));
        assert!(CODEX_HOOK_SOURCE.contains("raw_event_type"));
        assert!(CODEX_HOOK_SOURCE.contains("started"));
        assert!(CODEX_HOOK_SOURCE.contains("became_busy"));
        assert!(CODEX_HOOK_SOURCE.contains("requested_permission"));
        assert!(CODEX_HOOK_SOURCE.contains("ended"));
        assert!(!CODEX_HOOK_SOURCE.contains("provider_session_id"));
    }

    #[test]
    fn codex_hooks_profile_uses_codex_home_profile_file() {
        let home = std::path::Path::new("/Users/tester");
        let codex_home = codex_home_from(None, Some(home)).expect("Codex home should resolve");
        assert_eq!(codex_home, home.join(".codex"));

        let profile_path = codex_hooks_profile_path_for_home(&codex_home);
        assert_eq!(
            profile_path,
            home.join(".codex/openforge-lifecycle.config.toml")
        );
    }

    #[test]
    fn codex_hooks_profile_uses_documented_hook_events() {
        let script_path = std::path::Path::new("/Users/tester/.codex/openforge/openforge-hook.js");
        let profile = render_codex_hooks_profile(script_path);

        for event in [
            "[[hooks.SessionStart]]",
            "[[hooks.UserPromptSubmit]]",
            "[[hooks.PreToolUse]]",
            "[[hooks.PostToolUse]]",
            "[[hooks.PermissionRequest]]",
            "[[hooks.Stop]]",
        ] {
            assert!(profile.contains(event), "missing {event}");
        }

        assert!(profile.contains("matcher = \"startup|resume|clear|compact\""));
        assert!(profile.contains("matcher = \"*\""));
        assert!(profile.contains(
            "node \\\"/Users/tester/.codex/openforge/openforge-hook.js\\\" started SessionStart"
        ));
        assert!(profile.contains("became_busy UserPromptSubmit"));
        assert!(profile.contains("became_busy PreToolUse"));
        assert!(profile.contains("became_busy PostToolUse"));
        assert!(profile.contains("requested_permission PermissionRequest"));
        assert!(profile.contains("ended Stop"));
        assert!(profile.contains("timeout = 10"));
        assert!(!profile.contains("dangerously-bypass-hook-trust"));
    }

    #[test]
    fn codex_hooks_profile_defaults_to_full_access() {
        let script_path = std::path::Path::new("/Users/tester/.codex/openforge/openforge-hook.js");
        let profile = render_codex_hooks_profile(script_path);

        assert!(profile.contains("sandbox_mode = \"danger-full-access\""));
        assert!(profile.contains("approval_policy = \"never\""));
        assert!(!profile.contains("dangerously-bypass-approvals-and-sandbox"));
    }

    #[test]
    fn codex_hook_posts_normalized_payloads() {
        let payloads = evaluate_posted_payloads_for_events(&[
            ("started", "SessionStart"),
            ("became_busy", "UserPromptSubmit"),
            ("became_busy", "PreToolUse"),
            ("became_busy", "PostToolUse"),
            ("requested_permission", "PermissionRequest"),
            ("ended", "Stop"),
        ]);

        let kinds: Vec<&str> = payloads
            .iter()
            .map(|payload| payload["kind"].as_str().expect("kind should be string"))
            .collect();
        assert_eq!(
            kinds,
            [
                "started",
                "became_busy",
                "became_busy",
                "became_busy",
                "requested_permission",
                "ended"
            ]
        );
        assert_eq!(payloads[0]["provider"], "codex");
        assert_eq!(payloads[0]["task_id"], "T-CODEX");
        assert_eq!(payloads[0]["pty_instance_id"], 77);
        assert_eq!(payloads[4]["raw_event_type"], "PermissionRequest");
        assert!(payloads[0].get("provider_session_id").is_none());
    }

    fn evaluate_posted_payloads_for_events(events: &[(&str, &str)]) -> Vec<serde_json::Value> {
        let event_calls = events
            .iter()
            .map(|(kind, event)| format!("await postLifecycleEvent({kind:?}, {event:?});"))
            .collect::<Vec<_>>()
            .join("\n");
        let stdout = run_codex_hook_script(&format!(
            r#"
process.env.OPENFORGE_TASK_ID = "T-CODEX";
process.env.OPENFORGE_PTY_INSTANCE_ID = "77";
process.env.OPENFORGE_HTTP_PORT = "38123";
const payloads = [];
globalThis.fetch = async (_url, options) => {{
  payloads.push(JSON.parse(options.body));
  return {{ ok: true }};
}};
{event_calls}
process.stdout.write(JSON.stringify(payloads));
"#
        ));
        serde_json::from_str(&stdout).expect("payloads should be valid json")
    }

    fn run_codex_hook_script(script_body: &str) -> String {
        let source = CODEX_HOOK_SOURCE.replace("main();", "");
        let script = format!("{source}\n{script_body}");
        let script_file = tempfile::Builder::new()
            .prefix("openforge-codex-hook-test-")
            .suffix(".mjs")
            .tempfile()
            .expect("create Codex hook test script");
        std::fs::write(script_file.path(), script).expect("write Codex hook test script");
        let output = std::process::Command::new("node")
            .arg(script_file.path())
            .output()
            .expect("run node for Codex hook test");

        assert!(
            output.status.success(),
            "node failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        String::from_utf8(output.stdout).expect("node output should be utf8")
    }
}
