import { fireEvent, render, screen } from '@testing-library/svelte'
import { afterEach, describe, expect, it, vi } from 'vitest'
import AppToast from './AppToast.svelte'

describe('AppToast', () => {
  afterEach(() => {
    vi.useRealTimers()
  })

  it.each([
    { variant: 'error' as const, role: 'alert', live: 'assertive' },
    { variant: 'warning' as const, role: 'status', live: 'polite' },
    { variant: 'success' as const, role: 'status', live: 'polite' },
  ])('exposes $variant messages with the appropriate live-region semantics', ({ variant, role, live }) => {
    render(AppToast, { props: { message: `${variant} message`, variant, ondismiss: vi.fn() } })

    const toast = screen.getByRole(role)
    expect(toast.textContent).toContain(`${variant} message`)
    expect(toast.getAttribute('aria-live')).toBe(live)
  })

  it('dismisses after its configurable timeout, but not before', () => {
    vi.useFakeTimers()
    const ondismiss = vi.fn()
    render(AppToast, { props: { message: 'Timed message', variant: 'success', timeout: 1250, ondismiss } })

    vi.advanceTimersByTime(1249)
    expect(ondismiss).not.toHaveBeenCalled()
    vi.advanceTimersByTime(1)
    expect(ondismiss).toHaveBeenCalledOnce()
  })

  it('resets its timeout when the visible message is replaced', async () => {
    vi.useFakeTimers()
    const ondismiss = vi.fn()
    const view = render(AppToast, {
      props: { message: 'First message', variant: 'success', timeout: 1250, ondismiss },
    })

    vi.advanceTimersByTime(1000)
    await view.rerender({ message: 'Replacement message', variant: 'success', timeout: 1250, ondismiss })
    vi.advanceTimersByTime(1249)
    expect(ondismiss).not.toHaveBeenCalled()
    vi.advanceTimersByTime(1)
    expect(ondismiss).toHaveBeenCalledOnce()
  })

  it('does not dismiss after it is unmounted', () => {
    vi.useFakeTimers()
    const ondismiss = vi.fn()
    const view = render(AppToast, {
      props: { message: 'Unmounted message', variant: 'success', timeout: 1250, ondismiss },
    })

    view.unmount()
    vi.advanceTimersByTime(1250)
    expect(ondismiss).not.toHaveBeenCalled()
  })

  it('supports a labelled dismiss action', async () => {
    const ondismiss = vi.fn()
    render(AppToast, { props: { message: 'Dismiss me', variant: 'warning', ondismiss } })

    await fireEvent.click(screen.getByRole('button', { name: 'Dismiss notification' }))
    expect(ondismiss).toHaveBeenCalledOnce()
  })

  it('is not actionable when no click action is supplied', () => {
    render(AppToast, { props: { message: 'Informational only', variant: 'success', ondismiss: vi.fn() } })

    expect(screen.queryByRole('button', { name: 'Informational only' })).toBeNull()
  })

  it('runs its optional click action and dismisses', async () => {
    const onclick = vi.fn()
    const ondismiss = vi.fn()
    render(AppToast, { props: { message: 'Open task', variant: 'warning', onclick, ondismiss } })

    await fireEvent.click(screen.getByRole('button', { name: 'Open task' }))
    expect(onclick).toHaveBeenCalledOnce()
    expect(ondismiss).toHaveBeenCalledOnce()
  })

  it.each(['Enter', ' '])('handles the browser click generated by the %j key exactly once', async (key) => {
    const onclick = vi.fn()
    const ondismiss = vi.fn()
    render(AppToast, { props: { message: 'Open pipeline', variant: 'error', onclick, ondismiss } })
    const action = screen.getByRole('button', { name: 'Open pipeline' })

    await fireEvent.keyDown(action, { key })
    await fireEvent.keyUp(action, { key })
    await fireEvent.click(action)
    expect(onclick).toHaveBeenCalledOnce()
    expect(ondismiss).toHaveBeenCalledOnce()
  })

  it.each(['bottom', 'raised'] as const)('accepts the public %s positioning option', (position) => {
    const { container } = render(AppToast, {
      props: { message: `${position} toast`, variant: 'success', position, ondismiss: vi.fn() },
    })

    expect(screen.getByText(`${position} toast`)).toBeTruthy()
    expect(container.querySelector(`[data-position="${position}"]`)).not.toBeNull()
  })
})
